### ISSUE TITLE
Error alignment in main view

### ISSUE THREAD

**Issue by jim3ma** [hackjutsu/Lepton#100]
In main view:

![screen shot 2017-02-11 at 2 34 26 pm](https://cloud.githubusercontent.com/assets/1567113/22851775/5f575eaa-f067-11e6-8ff8-d5953775e3b5.png)

In line8, the `j "...` should be align with `openssl`.

In editing view, it's ok, but there are some redundant blank lines after line 11:

![screen shot 2017-02-11 at 2 35 01 pm](https://cloud.githubusercontent.com/assets/1567113/22851786/976bf72e-f067-11e6-8594-328eaaac811f.png)

**Comment by wujysh** [comment]
The first problem is a bug need to be resolved.
And the second one has been resolved in #89. Please wait for the next release:)

**Comment by hackjutsu** [comment]
The line number need to be wrapped inside a <td> other than <span> to make the alignment right.  I can improve this part.

**Comment by wujysh** [comment]
@hackjutsu 
Do you want to change the snippet view to CodeMirror powered editor with `readonly: true`?

**Comment by hackjutsu** [comment]
@wujysh That might be too heavy for the main view, especially when there are multiple files. If a simple fix works, let's keep it simple:)

**Comment by hackjutsu** [comment]
CodeMirror should be using the same techniques for line numbers. If it is using some other better trick, it is then a good educational moment to learn from it.

**Comment by wujysh** [comment]
@hackjutsu 
Yeah. That makes sense.

**Comment by hackjutsu** [comment]
Should be fixed:https://github.com/hackjutsu/Lepton/commit/31b967fd407f1e75fe81552b3cc7eed146ee05b7

**Comment by hackjutsu** [comment]
![image](https://cloud.githubusercontent.com/assets/7756581/22865614/ddcf4242-f135-11e6-892f-91ad5dbb9e8f.png)

**Comment by jim3ma** [comment]
Great!
