### ISSUE TITLE
Get imbed link

### ISSUE THREAD

**Issue by mikeerickson** [hackjutsu/Lepton#102]
I don't see it there now, perhaps there is a way to get the raw link so that I can do a quick `wget ...`

Further, how about links for `wget` and `curl` as to get access quickly from terminal

**Comment by hackjutsu** [comment]
We can add a #copy_raw_link button on the raw modal.

**Comment by mikeerickson** [comment]
@hackjutsu that would be swell 👍

**Comment by hackjutsu** [comment]
Done: 9b95e98ce045b35e3265b2071d5952d41d433f95
