### ISSUE TITLE
#edit link opens window offscreen

### ISSUE THREAD

**Issue by mikeerickson** [hackjutsu/Lepton#103]
While I am able to scroll window down, I am thinking the opened dialog should not expand outside of the window bounds.

![image](https://cloud.githubusercontent.com/assets/183153/22865318/4dfc4a12-f116-11e6-8bd5-e946245afb28.png)

![image](https://cloud.githubusercontent.com/assets/183153/22865320/5b0549e8-f116-11e6-8d61-c449e8e428b8.png)

**Comment by hackjutsu** [comment]
Not supported by Electron framework.

**Comment by mikeerickson** [comment]
@hackjutsu so that initial dialog window size is not your definition.  I see based on the amount of content, the window size varies?

**Comment by hackjutsu** [comment]
@mikeerickson 

We can set the **initial** size for the window in the main process, after that it's up to user to resize the windows by dragging.

**Comment by mikeerickson** [comment]
@hackjutsu what I am seeing here, the `edit` window is MUCH larger than my resized application window.

This file has 95 lines, however, the edit window stops at line 30 which is the bottom of my MBP screen.

![image](https://cloud.githubusercontent.com/assets/183153/22865961/d0df694e-f122-11e6-8ba7-8e7d58728c19.png)

**Comment by hackjutsu** [comment]
You have to scroll down in this case~

**Comment by wujysh** [comment]
@hackjutsu 
If the gist contains plenty of long files, it's quite difficult to find the `Submit` button.
