### ISSUE TITLE
Display last edit date 

### ISSUE THREAD

**Issue by mikeerickson** [hackjutsu/Lepton#104]
Would be nice to have the last edit day displayed in the list on left AND in detail page.

**Comment by hackjutsu** [comment]
We're not going to show the history revisions on the app (you can navigate to there by the #revisions button). In this sense, it might not have much value for showing the last edit day IMHO.

**Comment by mikeerickson** [comment]
@hackjutsu I dont need whole revision history, last the last edit date for the current gist.   And yes, the revision history can be seen with a simple click (which opens the page in browser).

**Comment by wujysh** [comment]
@hackjutsu 
I think we should display information that GitHub's online Gist page displays.
![image](https://cloud.githubusercontent.com/assets/5550402/22870927/1a18ad5e-f1e7-11e6-9e4a-dc0de6e22648.png)

**Comment by hackjutsu** [comment]
@wujysh @mikeerickson 

When we have a setting page in the future release, I'll add an option to turn on/off the `last edit date`, and maybe some other information.

**Comment by hackjutsu** [comment]
Done: https://github.com/hackjutsu/Lepton/commit/6e18ec097b328266eb0f44cd55c262586c3fab7e
