### ISSUE TITLE
Feature request: Star a gist and list starred gists

### ISSUE THREAD

**Issue by wujysh** [hackjutsu/Lepton#106]
Any plans to support star a specific gist and show starred gists?
The list can be displayed as the first tag as `*star`?

### Related GitHub APIs
* List starred gists
> https://developer.github.com/v3/gists/#list-starred-gists
* Check if a gist is starred
> https://developer.github.com/v3/gists/#check-if-a-gist-is-starred
* Star a gist
> https://developer.github.com/v3/gists/#star-a-gist
* Unstar a gist
> https://developer.github.com/v3/gists/#unstar-a-gist

**Comment by hackjutsu** [comment]
I don't think that's useful actually. I never use them...

**Comment by hackjutsu** [comment]
Maybe I would like to provide a link to original gist online.

**Comment by hackjutsu** [comment]
f8624a27d4920f6604d6e1f7db967bf952a67850
