### ISSUE TITLE
Provide a method to navigate to the gist online

### ISSUE THREAD

**Issue by hackjutsu** [hackjutsu/Lepton#107]
Provide a method for users to navigate to the gist online, so that users can access advanced features there. (Get embedded link, Star, etc.)

![image](https://cloud.githubusercontent.com/assets/7756581/22890651/02b0a8d0-f1db-11e6-8f35-72889c90cd02.png)

**Comment by wujysh** [comment]
@hackjutsu 
Will it conflict with #74 ?

**Comment by hackjutsu** [comment]
@wujysh There will be an extra button for collapse/expand :)

**Comment by wujysh** [comment]
@hackjutsu 
What about change the `#raw` to `#more` or something else? Does `#raw` page have any meaning now?

**Comment by hackjutsu** [comment]
@wujysh 

That is a good point. I like to use the `#raw` to perform a non-rich text copy for a fraction of the snippet, especially when the snippet is long.

Sorry for keeping some personal preference in the app... Maybe we can either
- change `#revisions` to `#more`
- or change filename to a link to the online gist

**Comment by hackjutsu** [comment]
I changed the `#revisions` to `#starred`, which navigate the user to their starred gists online.

**Comment by wujysh** [comment]
@hackjutsu 
I don't think `#starred` should be placed on gist view panel, because it's irrelevant to specific gist.
IMHO, it should be placed on the left panel.

**Comment by hackjutsu** [comment]
@wujysh 

Good thought:) Might move it to the left panel once I get https://github.com/hackjutsu/Lepton/issues/55 done.
