### ISSUE TITLE
homebrew formula for Lepton.app ?

### ISSUE THREAD

**Issue by Fil** [hackjutsu/Lepton#116]
Please consider adding a brew formula. One issue is that brew already has [https://github.com/dropbox/lepton](https://github.com/dropbox/lepton) as `lepton`.

**Comment by hackjutsu** [comment]
Ha-ha, it's hard to come up with a unique name .

**Comment by hackjutsu** [comment]
https://github.com/Homebrew/brew/blob/master/docs/Formula-Cookbook.md

**Comment by passerbyid** [comment]
I think that [Homebrew Cask](https://github.com/caskroom/homebrew-cask) is a better choice.

I can handle it, but I need a name that comply [Homebrew Cask's rule](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/name.md). And this name can't be a duplicated with a homebrew formula. As @Fil said,  `lepton` has been taken.

**Comment by hackjutsu** [comment]
What about `lepton-app`?

**Comment by passerbyid** [comment]
I thought about `lepton-app`，but I'm afraid that this name will be confused with dropbox's lepton.

**Comment by hackjutsu** [comment]
@passerbyid 

That's a good point. 

We can put the `homebrew`/`Homebrew Cask`'s instructions on README with the explicit name `lepton-app` . Users are likely to use `homebrew`/`Homebrew Cask` to install Lepton after the reading there, other than searching for our Lepton on `homebrew` directly.

For people trying to install Dropbox's Lepton, I don't think `lepton-app` would confuse them, since it's hard to associate Dropbox's Lepton with an app.

**Comment by passerbyid** [comment]
Okay, I have sent a pull request to homebrew-cask.

caskroom/homebrew-cask#30575

**Comment by vitorgalvao** [comment]
> And this name can't be a duplicated with a homebrew formula.

We don’t have any rule that prohibits a cask and a formula from sharing a name. Additionally, the token (what you use to install) is derived from our [token reference](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md), to prevent duplicates. `lepton-app` would not be acceptable in this case.

The cask in https://github.com/caskroom/homebrew-cask/pull/30575 has been merged.

**Comment by passerbyid** [comment]
@vitorgalvao Thanks!

**Comment by hackjutsu** [comment]
Thank you guys!

**Comment by hackjutsu** [comment]
Do we need to send a new PR for each new release?

**Comment by vitorgalvao** [comment]
> Do we need to send a new PR for each new release?

Yes. *But* if you [use `cask-repair`](https://github.com/caskroom/homebrew-cask/blob/master/CONTRIBUTING.md#updating-a-cask) it’s literally one command away, that you can run in any directory, or even as part as your deployment.

Run one (for installation and setup):

```bash
brew install vitorgalvao/tiny-scripts/cask-repair
cask-repair --help
```

Then whenever you update Lepton, you need only:

```
cask-repair -v {{new_version_here}} -b lepton
```

And it’ll do everything for you automatically, including submitting the PR.

**Comment by hackjutsu** [comment]
@vitorgalvao Nice！Thanks for your explanation:)
