### ISSUE TITLE
Task List Markdown Rendering

### ISSUE THREAD

**Issue by kevinchau321** [hackjutsu/Lepton#117]
Task lists / to-do lists aren't rendering from markdown correctly. They should behave like this:
https://github.com/blog/1825-task-lists-in-all-markdown-documents

**Comment by hackjutsu** [comment]
Thanks for reporting the bug,  I'll follow up with it.

**Comment by kevinchau321** [comment]
Its probably because its GitHub Flavored Markdown. I'm curious, how will you go about implementing this feature? Thanks.

**Comment by hackjutsu** [comment]
@kevinchau321 It depends on the [marked](https://github.com/chjj/marked) package.

**Comment by hackjutsu** [comment]
https://github.com/jonschlinkert/remarkable

**Comment by xcatliu** [comment]
I would vote to markdown-it, it has a lot of plugins

**Comment by hackjutsu** [comment]
@xcatliu PR is welcome!

**Comment by cixuuz** [comment]
markdown-it seems ok. But should we add this checkbox plugin as default?

**Comment by hackjutsu** [comment]
@cixuuz Yes, please
