### ISSUE TITLE
Don't ask for switching account on startup

### ISSUE THREAD

**Issue by uetchy** [hackjutsu/Lepton#118]
It is inconvenient to click 'Continue as ...' button every time even if I have only one account for gist.
Switching account should be provided via somewhere like application menu, not on startup.

**Comment by hackjutsu** [comment]
@uetchy Just hit Enter.

**Comment by hackjutsu** [comment]
Might want this open for discussion.

**Comment by wujysh** [comment]
I think an auto login option should be provided.
