### ISSUE TITLE
New design?

### ISSUE THREAD

**Issue by hackjutsu** [hackjutsu/Lepton#119]
Thanks @AngieW0908 !

![wechatimg1](https://cloud.githubusercontent.com/assets/7756581/23571788/06472822-0020-11e7-8364-7e0f8a2f023c.jpeg)

**Comment by DNLHC** [comment]
I've been tweaking around with styles for my personal use
![GitHub Logo](http://i.imgur.com/jinuFia.jpg)

**Comment by hackjutsu** [comment]
@DNLHC 

Wow, that looks gorgeous! Would you consider sending a PR?

--Cosmo

**Comment by DNLHC** [comment]
@hackjutsu 
Yeah, i would love to
Let me know if you wanna keep monospaced font for the interface, i changed it because on my system it was quite unreadable

**Comment by hackjutsu** [comment]
@DNLHC I don't have a strong preference for that. If you have a better font style, I would love to have a try.
