### ISSUE TITLE
Cannot login

### ISSUE THREAD

**Issue by kocoai** [hackjutsu/Lepton#120]
Hello,

I cannot select Authorize Application for Lepton. The button is inactive.
 
<img width="487" alt="screen shot 2017-03-04 at 22 49 58" src="https://cloud.githubusercontent.com/assets/222427/23582551/1f3461e8-012d-11e7-867a-521f7dd26292.png">

**Comment by hackjutsu** [comment]
@kocoai 

Interesting... The page is provided by GitHub which is out of my control. Maybe there is a limit for authorized users per app? Sorry, I need to further confirm with GitHub about the possible issues.

**Comment by kocoai** [comment]
It seem there is an error in github oauth. Here is the error in the console "Uncaught Error: invariant requires an error message argument" (line 3088, in the .txt file in attachment)

[oauth.txt](https://github.com/hackjutsu/Lepton/files/818968/oauth.txt)

**Comment by hackjutsu** [comment]
@kocoai 

Thanks for providing the information. I have contacted GitHub and will investigate this issue this weekend.

**Comment by carolineartz** [comment]
I was able to get around this by registering a github app, building locally, and a little finagling 

After building locally I got the same disabled button and error in the console. But, copying the auth request uri into a regular browser (e.g., Chrome, `https://github.com/login/oauth/authorize?client_id=[MY_CLIENT_ID]&scope=gist`) made the difference. The auth page rendered with the button enabled. After I authenticated, I went back to the Lepton app and refreshed and now I'm in.

Didn't say it was pretty ...

**Comment by hackjutsu** [comment]
@carolineartz 

Thanks for the investigation. I couldn't find issues on Lepton's side at this moment. I suspect GitHub's cdn delivers different js files for the web and the electron app...

**Comment by kocoai** [comment]
Here is my workaround binary version (1.2.0):

- open in firefox https://github.com/login/oauth/authorize?client_id=[replace_with_the client_id_found_in console]&scope=gist
- select "Authorize application" (enabled)
- return back in Lepton and login

**Comment by hackjutsu** [comment]
@kocoai @carolineartz 

The issue is caused by the recent update of GitHub's auth server. Could you help me verify [this fix](https://github.com/hackjutsu/Lepton/commit/db62c98eac72bce9959274d8e112876f5f7e457c) work on your side?

If that works, I can publish a new release for that 👌

**Comment by carolineartz** [comment]
@hackjutsu yes it looks like your fix is good. I made the same change locally, repacked, and was able to authenticate as expected. 👍

**Comment by kocoai** [comment]
Yes!  I confirm (tardily) version 1.2.1 fix the login issue :) . Great work !

**Comment by SergiuTigan** [comment]
> Here is my workaround binary version (1.2.0):
> 
> * open in firefox [https://github.com/login/oauth/authorize?client_id=[replace_with_the_client_id_found_in_console]&scope=gist](https://github.com/login/oauth/authorize?client_id=%5Breplace_with_the_client_id_found_in_console%5D&scope=gist)
> * select "Authorize application" (enabled)
> * return back in Lepton and login

How do i get the client id? i can't open the console...

**Comment by bjulian5** [comment]
@SergiuTigan 
On the page with the disabled button, click on toggle developer controls and then inspect the elements for the button. You should be able to find the client ID there

**Comment by delta-develop** [comment]
What if I have a Mac and the Authorization screen opens in Safari (no inspector)
