### ISSUE TITLE
Simple syntax for tags, like #tag1, #tag2

### ISSUE THREAD

**Issue by kocoai** [hackjutsu/Lepton#121]
Hi,

First, thank you for the excellent snippet app 🎉

It's clever to support tags in the snippet tittle. Could you add the possibility to write tags shorter `#tag1, #tag2, #tag3...` instead of `#tags: tag1, tag2, tag3` ?

**Comment by hackjutsu** [comment]
Thanks @kocoai 👍  

We plan to add an extra field for tags, so that users don't have to enter `#tags: tag1, tag2, tag3` at the end of the description.

**Comment by hackjutsu** [comment]
https://github.com/hackjutsu/Lepton/issues/65

**Comment by Offirmo** [comment]
Could you trim the tags ? Using `#tags: foo, bar` gives tags _foo and _bar (visible on alignment on the tag list on the left)

**Comment by hackjutsu** [comment]
@Offirmo 

Could you give me a screenshot? Usually, Tags are [trimmed](https://github.com/hackjutsu/Lepton/blob/master/app/utilities/parser/index.js#L51) before they are stored. Maybe I have missed something here.

**Comment by Offirmo** [comment]
Sure:

<img width="516" alt="capture d ecran 2017-05-26 a 11 00 47" src="https://cloud.githubusercontent.com/assets/603503/26478999/b6d10734-4202-11e7-8a0c-49f827f20307.png">

<img width="524" alt="capture d ecran 2017-05-26 a 11 01 12" src="https://cloud.githubusercontent.com/assets/603503/26479006/c2fd457c-4202-11e7-8653-8f0a6296f40e.png">

Ah... looking at it, it may be a eol issue on a non-comma-separated tag ;)

**Comment by Offirmo** [comment]
Btw can't a parser taking every space-separated word beginning with # be enough for detecting tags ?

ie `my great gist #JS #foo #Bar`

**Comment by Offirmo** [comment]
BTW bis, Lepton is an amazing tool which completed nicely my existing toolset (a GitHub Wiki + a GitHub "quick test" project)

Thanks for your sharing !!!

**Comment by hackjutsu** [comment]
Thanks @Offirmo :) 

I'm working on the `#myTag` style. The difficult part for `#myTag` is the separation between non-English words. 

[twitter-text-js](https://github.com/twitter/twitter-text/tree/master/js) seems to provide a pretty support for that. If you like, you can send a PR.

**Comment by hackjutsu** [comment]
@Offirmo @kocoai 

If you are still interested, could you have a try for this beta release? It comes with the support for the twitter tags style.

https://github.com/hackjutsu/Lepton/releases/tag/v1.3.0-beta

**Comment by Offirmo** [comment]
@hackjutsu that's good but I think we could go further. Right now, when not using [], the text I type is taken as description. It should be defaulted as the title:

Short syntax `Javascript sets #JavaScript`
* tags: `#JavaScript`
* title: `Javascript sets #JavaScript` (tags kept since we don't know if they are part of the sentence)
* description: (none)

Full Syntax `[Javascript sets] A demo of sets #JavaScript`
* tags: `#JavaScript`
* title: `Javascript sets`
* description: `A demo of sets #JavaScript` (tags kept since we don't know if they are part of the sentence)

But this is a minor feature! Don't bother if you don't have time!

**Comment by hackjutsu** [comment]
@Offirmo Thanks for testing!

For the short syntax `Javascript sets #JavaScript`, what if users have a long description which is not suitable to put as a title?

**Comment by kocoai** [comment]
Work like a charm in 1.3.0 thank you !!

**Comment by hackjutsu** [comment]
@kocoai Thanks for testing!
