### ISSUE TITLE
Add Lepton 1.3.0 to brew cask

### ISSUE THREAD

**Issue by hackjutsu** [hackjutsu/Lepton#127]
https://github.com/hackjutsu/Lepton/issues/116

**Comment by passerbyid** [comment]
I think this issue should be closed.

https://github.com/caskroom/homebrew-cask/pull/35177

**Comment by hackjutsu** [comment]
@passerbyid Thanks!

**Comment by hackjutsu** [comment]
@passerbyid What's the command to use brew cask again? I would like to put it in the release note:)

**Comment by passerbyid** [comment]
@hackjutsu 
Just use `brew cask install lepton` . I think you should add a _Install_ section for users in README for that, like [this](https://github.com/MacDownApp/macdown#install).
