### ISSUE TITLE
Add ability to make new private gists by default

### ISSUE THREAD

**Issue by SilverBut** [hackjutsu/Lepton#130]

**Comment by hackjutsu** [comment]
@SilverBut 

Thanks for suggestion ;) Yes, it should be simple to implement if there is a setting panel. There was a story for that, but I'm unfortunately busy with other projects.

If you like to help, I can give you some guidelines.

**Comment by SilverBut** [comment]
Never learned JavaScript before. Only understand C, C, and C. However I'll try to see if I can help.

**Comment by hackjutsu** [comment]
@SilverBut 

Thanks, it might take some effort to catch up if you don't have background in JS. Some knowledge in Electron and React is necessary to begin. Let me know if you are still interested.

**Comment by SilverBut** [comment]
Yes. Still busy on my exam, so will not work immediately. But I have a plan...

I think Electron is a "portable chrome", and though I haven't used JS to write any web-based apps, I do know something such as modifying DOM trees. So I will try to do these things:

* Find out where the tokens are saved. Maybe saved in JSON format? Or in the local storage? Anyway, since the DB model usually used in JS is always performing like a JSON object, it should be easy to add a new key-value pair into it.
* Find out the controller and implement some methods such as `bool getParameterIfNewGistPrivate(void)` (only a example, lol
* Add related code to the constructor of the New Gist interface and set `UI_NewGist->private` according to the key-value pair
* Add a new setting dialog box, which is basically repeating those steps, calling related functions

Did I get the point?

**Comment by hackjutsu** [comment]
Lepton uses Redux to control its app states. 

We can persist the settings in either a JSON file or localStorage. When the app is launched, we can read the settings and initialize to the Redux state accordingly.

**Comment by SilverBut** [comment]
Roger. Will do it next week.

**Comment by hackjutsu** [comment]
@SilverBut In my opinion, this issue https://github.com/hackjutsu/Lepton/issues/121 might be easier to begin with.

**Comment by SilverBut** [comment]
@hackjutsu However I'm already working on this, lol

Besides, would it be okay if I use "About" box as the config panel? Since it looks like a configuration panel but since there is nothing to config, it is used as a about box...

**Comment by hackjutsu** [comment]
@SilverBut 

Yes, the about panel is originally designed for "Settings". You can simply add a new tab there.
There is an existing local file for preference, which you can add extra fields.
https://github.com/hackjutsu/Lepton/blob/dev/app/index.js#L59

**Comment by SilverBut** [comment]
Wow, just looking for it. thx.

**Comment by hackjutsu** [comment]
Now we can put this default "private" config in `<home>/.leptonrc`.

https://github.com/hackjutsu/Lepton/blob/master/app/utilities/githubApi/index.js#L13

**Comment by skamv** [comment]
@hackjutsu how is that information structured in leptonrc? I want to put the default "private"

**Comment by hackjutsu** [comment]
Check out 1.4.3-alpha-9 and the [template for .leptonrc](https://gist.github.com/hackjutsu/1ad7e4968eb64d881ec9dedd6c0f400b). Change the `newSnippetPrivate` field to true.
