### ISSUE TITLE
Question about sorting of snippets

### ISSUE THREAD

**Issue by SilverBut** [hackjutsu/Lepton#131]
There are two snippets with the same tags. When viewing tag `reverse`:

* Script 1: `#tags: IDAPython, IDA, reverse, powerpc, ppc, analysis`
* Script 2: `#tags: 233, analysis, reverse`

And when lising tag `analysis`, the sort is inverted. 

Is a feature or bug?

(In fact it can be a feature if an option is provided to control its behavior)

**Comment by hackjutsu** [comment]
@SilverBut 

If I understand your question correctly, you are asking about how Lepton orders the gists.

Lepton doesn't apply special ordering to the gists. It should keeps their original order when downloaded from the Gist server, which according to my observation, is ordered by their modified/created timestamp.

**Comment by SilverBut** [comment]
Seems some strange inconsistent between my local client and server...clear all data and resync, then everything is fine.

**Comment by hackjutsu** [comment]
@SilverBut 

The order will be a little bit difference if we create or edit a gist locally. The local copy of the updated gist will be added to the front/back of the internal storage, which will make the order out of sync. The issue will automatically fixed after a re-sync.
