### ISSUE TITLE
JavaScript Error when launch the app

### ISSUE THREAD

**Issue by kingname** [hackjutsu/Lepton#132]
![1](https://cloud.githubusercontent.com/assets/5440523/25689254/07b8b3f0-30b9-11e7-8ecd-d7186db58ebf.png)

When I launch the app, there is an alarm box appear like above.

**Comment by hackjutsu** [comment]
Thanks for reporting:)

It looks like the app was re-launched from the dock. Can you give me more details about how to reproduce the bug?

**Comment by kingname** [comment]
This bug does not always appear. Only when I reboot my mac book pro 2016 and then launch the app from the Launchpad at the first time, it does. And If I launch it from dock, or even I close it from dock , and  launch it from launchpad again, everything is ok.

My System is 10.12.4

**Comment by hackjutsu** [comment]
I cannot reproduce it at this moment. But I'll keep an eye on it.

**Comment by kingname** [comment]
OK. I will close this issue now.

**Comment by hackjutsu** [comment]
Related issue: https://github.com/electron/electron/issues/5272

**Comment by kingname** [comment]
Sounds like that you have already found the reason and know how to fix it. So This issue can be closed.
