### ISSUE TITLE
.ahk file have no code highlighting

### ISSUE THREAD

**Issue by waldens** [hackjutsu/Lepton#136]
On the home page, `.ahk` files do not have code highlighting. The edit page also has no code highlighting.

![s1](http://onuia4d7l.bkt.clouddn.com/2017_05_25_20170525041317.png)
![s2](http://onuia4d7l.bkt.clouddn.com/2017_05_25_20170525041631.png)

**Comment by hackjutsu** [comment]
Lepton uses `highlight.js` for syntax highlight. 

As far as I know, `.ahk` [is not supported](https://highlightjs.org/static/demo/) at this moment. Maybe [highlight.js's GitHub repo](https://github.com/isagalaev/highlight.js) would be a better place for a new language support request. We are more than happy to update its version once ready, or you can send a PR then.

**Comment by waldens** [comment]
@hackjutsu Thanks for reply! I checked, and seems `AutoHotkey` is supported by highlight.js, right?:

![s1](http://onuia4d7l.bkt.clouddn.com/2017_05_25_20170525050409.png)

**Comment by hackjutsu** [comment]
You are right. Let's reopen this issue.

**Comment by hackjutsu** [comment]
The syntax highlight works for me. Could you share your gist link so that I can fork and test on my side?

<img width="717" alt="jietu20170524-151242" src="https://cloud.githubusercontent.com/assets/7756581/26427829/6e7a5b68-4093-11e7-9567-d85bf05d1165.png">

**Comment by hackjutsu** [comment]
The syntax highlight only works for the first part. 

```autohotkey
; 重点看base的用法，base表示基类，表示继承关系
Month := {}
days := {day1:"Sun",day2:"Mon",day3:"Tues",day4:"Wed",day5:"Thurs",day6:"Fri",day7:"Sat", base:{ parent: Month }}
```

This has something to do with how `highlight.js` parses the `.ahk` syntax.  I'll recommend file an issue there.

**Comment by waldens** [comment]
@hackjutsu  Thanks to test! Gist: https://gist.github.com/69f97e813d88e912861c68f407e470b6

It seems `highlight.js`'s fault. `highlight.js` does not highlight the `Class` and `Object` syntax in Autohotkey, only highlight some basic syntax. I'll discuss this problem in `highlight.js` repository.
 
Only last question, is there syntax highlighting in the `#edit` interface? Because I tried `test.ahk` you provided, there is no syntax highlighting in the `#edit`.

![s1](http://onuia4d7l.bkt.clouddn.com/2017_05_25_20170525063417.png)

**Comment by hackjutsu** [comment]
@waldens 

Maybe not for [CodeMirror](https://github.com/codemirror/CodeMirror/tree/master/mode)(Lepton's editor).
