### ISSUE TITLE
Broken link for license file in Lepton 1.3.0

### ISSUE THREAD

**Issue by hackjutsu** [hackjutsu/Lepton#138]
The link is looking for the `LICENSE.md` which has however renamed to `LICENSE`.

https://github.com/hackjutsu/Lepton/blob/master/app/containers/settingPage/index.js#L35

**Comment by passerbyid** [comment]
I think this could be resolved by removing `.md`.

**Comment by hackjutsu** [comment]
@passerbyid 

Yes, that's it. I keep it open since it is a convenient PR, if someone wants to gain some experience on an open source project. (Like forking & send a PR on GitHub)

**Comment by passerbyid** [comment]
Got it, appreciate it.
