### ISSUE TITLE
Suggestion: Add an apt repository

### ISSUE THREAD

**Issue by sbrl** [hackjutsu/Lepton#139]
An apt repository would make it easy for users of debian derivatives to install Lepton. In addition, it _should_ be fairly trivial to set up, I should have thought - since Lepton for linux is distributed as a single binary already. Tools exist to automatically generate packages for multiple linux-based systems at once, too.

**Comment by hackjutsu** [comment]
@sbrl 

Thanks for suggestion ;) Is there any problem when using the AppImage format in Debian? 

Since I don't have a Debian system for testing, I would prefer a format that can run everywhere for different Linux.  ([AppImage](http://appimage.org/) is the best option I can find at this moment.)

**Comment by sbrl** [comment]
@hackjutsu Nope, there isn't a particular problem with it! It's just that since I am on a debian-based system (Ubuntu 17.04, actually), I much prefer to have everything update through `apt` - that way I only have 1 thing to keep track of to update my laptop here. Other distributions will be the same - just with different package manager.

The AppImage system you're using currently looks like it it would lend itself quite well to automatic packaging.

**Comment by hackjutsu** [comment]
I would like to keep this post open to see whether other people have similar requests.

Related issues:
https://github.com/hackjutsu/Lepton/issues/57
https://github.com/hackjutsu/Lepton/issues/127
