### ISSUE TITLE
Function request: Preview + Toolbar

### ISSUE THREAD

**Issue by stonedreamforest** [hackjutsu/Lepton#140]
1.  please add “preview”
2.  and like this：

![222222](https://user-images.githubusercontent.com/16742566/27063831-9ef45fb2-5026-11e7-96f7-932b66943432.png)

**Comment by hackjutsu** [comment]
@stonedreamforest 

Thanks  for suggestion;) It requires significant refactoring for this support, which I don't expect to happen in the near future.

If you are looking for a good markdown editor, I would recommend [Marxico](https://marxi.co/).

**Comment by stonedreamforest** [comment]
Marxico looks good :+1:  
i like Marxico ,but I prefer like Lepton. Looking forward to the next or next next release
