### ISSUE TITLE
Automatic updates

### ISSUE THREAD

**Issue by peterschussheim** [hackjutsu/Lepton#141]
I would love to see Lepton gain the ability to automatically check for updates and install updates rather than making the user download a fresh binary.  I believe zeit [Hyper](https://github.com/zeit/hyper) and [Now](https://github.com/zeit/now) have this feature.  I would be happy to work on this feature; I will search for useful resources and would appreciate any feedback from contributors.

## Notes
- [electron-builder](https://github.com/electron-userland/electron-builder) looks like it supports automatic updates out-of-the-box and is actively maintained.
- [Electron automatic updates](https://github.com/electron/electron/blob/master/docs/api/auto-updater.md)

**Comment by hackjutsu** [comment]
@peterschussheim 

Thanks for the suggestion! This is actually a good point. 

Lepton was planned to adopt [electron-builder's auto-update feature](https://github.com/electron-userland/electron-builder/wiki/Auto-Update). However, I didn't get it well tested on all platforms for the first release (Win/macOS/Linux). 

I implemented the first part for the auto-updating, which uses `electron-updater` to check for the new release, but without the actual download and installation.
https://github.com/hackjutsu/Lepton/blob/master/main.js#L15

This workaround works so far so good as Lepton isn't released pretty often. But I would love to see a full-fledged auto-update support. (PR is welcome~)

**Comment by hackjutsu** [comment]
https://github.com/hackjutsu/Lepton/commit/a41ec314c3906f372ca4fc2c521f524f03b9ae6f
