### ISSUE TITLE
Can I use a github personal access token to login ?

### ISSUE THREAD

**Issue by mohanraj-r** [hackjutsu/Lepton#145]
I am using the osx app - and I am not sure how to login to the app. 
Tried generating and using [Personal Access Tokens](https://github.com/settings/tokens) - but it didn't work. 

As per the doc 
>  Register your application, and put your client id and client secret in ./configs/account.js

* But do we have to register a oauth app? What would be the callback URL in that case?
* Where should the `./configs/account.js` be placed in osx ?

**Comment by hackjutsu** [comment]
Hi @mohanraj-r , thanks for having a try :)

For the OSX app, just download and install the latest version [here](https://github.com/hackjutsu/Lepton/releases), and it'll show up a login prompt after launch.

**Comment by mohanraj-r** [comment]
Hi @hackjutsu 
I do have the osx app installed. But when I open it it is prompting for the username and password. 
I want to know how / if I can use the personal access token to login ?
E.g. [Gisto](http://www.gistoapp.com/faq/) login screen has a "Enter Access Token" button which I can use to directly enter a personal access token without entering the username and password. 

How can I do this with lepton ?

**Comment by hackjutsu** [comment]
Lepton will exchange for its own token for the first time, and use the cached token for the following launches. 

Unfortunately, the second part happens internally and not exposed to the user interface yet.

_Sent from my BlackBerry BBB100-1 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by mohanraj-r** [comment]
Ah, thats unfortunate. I would really like to give Lepton a try. 
But I don't like giving my creds out and also have 2FA enabled.

**Comment by hackjutsu** [comment]
I understand your concerns :)

They are essentially the same in OAuth2.0... The client won't have your credentials but only the access token. However, 2FA is not supported in this way.
