### ISSUE TITLE
[FeatureRequest] for shortcut keys of 'Submit' button and 'Delete line' operation in Editor dialog

### ISSUE THREAD

**Issue by wezhang** [hackjutsu/Lepton#149]
Thanks for the brilliant tool!

May I request the feature for shortcut keys of 'Submit' button and 'Delete line' operation in Editor dialog?

Thanks!

**Comment by hackjutsu** [comment]
Hi @wezhang, thanks for this feature request :)

Yes, the 'Submit' shortcut would be pretty helpful. But what do you mean by saying 'Delete line' operation? Do you mean like 'dd' in Vim?

**Comment by wezhang** [comment]
@hackjutsu , I mean that 😄 , but I know there is no mode switch like Vim, so, the 'Delete line' is more like 'Shift + Delete' in Visual Studio Code.

**Comment by wujysh** [comment]
@wezhang Delete line operation has already been supported by CodeMirror. :)
Shortcut: `Ctrl-D` (PC), `Cmd-D` (Mac)

**Comment by wezhang** [comment]
@wujysh Thanks! `Ctrl-D` works! Looks like we need a shotcut list page. 👍

**Comment by hackjutsu** [comment]
@wezhang That's a good idea:)

**Comment by hackjutsu** [comment]
https://github.com/hackjutsu/Lepton/issues/177
https://github.com/hackjutsu/Lepton/issues/176

**Comment by hackjutsu** [comment]
https://github.com/hackjutsu/Lepton/commit/a581b4705bee21cebd8a06f46185642abe27ca52
