### ISSUE TITLE
Make "SECRET GIST" more noticeable

### ISSUE THREAD

**Issue by hackjutsu** [hackjutsu/Lepton#153]
![jietu20170723-225600](https://user-images.githubusercontent.com/7756581/28510015-afe4e41a-6ffa-11e7-8f5c-c6450858584d.jpg)

It's hard to tell the difference between a public gist and a secret gist without carefully inspecting the title bar. We might need some way to highlight the secret gist.

- Change the bar color?
- Change the font color?

**Comment by wezhang** [comment]
Adding a special icon beside the title? like a ㊙️ or 🔒 ?

**Comment by hackjutsu** [comment]
Maybe the "LOCK" from [Evil icons](http://evil-icons.io/) ?

**Comment by wezhang** [comment]
It's nice. 👍
