### ISSUE TITLE
Same padding for both edges?

### ISSUE THREAD

**Issue by hackjutsu** [hackjutsu/Lepton#156]
![jietu20170724-213402](https://user-images.githubusercontent.com/7756581/28555962-ed51bd92-70b7-11e7-8745-303237647565.jpg)

I know this is a little bit picky, but I still like both edges to share the same padding.

**Comment by DNLHC** [comment]
@hackjutsu 
It actually has the same padding from both sides, the arrow icon is the issue it has some white space around it. I'll redraw arrow later.
