### ISSUE TITLE
Use icons for buttons?

### ISSUE THREAD

**Issue by hackjutsu** [hackjutsu/Lepton#159]
![jietu20170724-231944](https://user-images.githubusercontent.com/7756581/28558405-a0be6b56-70c6-11e7-9658-b02420d33e06.jpg)

**Comment by Alaev** [comment]
I don't think it will be a good idea to switch them to buttons.
However, I can see the need to put some background around it and make it more as a pill/tag.
For example like so: 
![example](https://www.dropbox.com/s/8g8eu523ilvejob/Screenshot%202017-07-25%2009.52.11.png?dl=1)

**Comment by hackjutsu** [comment]
@Alaev 

Thanks for your advice;)  But why do you think it would be better to make it more like a tag? I think they are essentially buttons, and would be nice to keep consistent with other buttons to use icons, like:

![jietu20170724-235846](https://user-images.githubusercontent.com/7756581/28559662-52604de8-70cc-11e7-8ac4-682edca50899.jpg)

**Comment by Alaev** [comment]
I think it's just more twitter and facebook like #(hash) it's not a real button, however, it has some interaction that is useful to the user, for example, clicking on it will take you to all the tags associated with that string.
For example, you can see the # use in the boostnote app.
![boostnote](https://www.dropbox.com/s/ruh9n1nfcxere2v/Screenshot%202017-07-25%2010.04.54.png?dl=1)

**Comment by Alaev** [comment]
I have taken a double look at the issue and it would be a good implementation to transfer the UI of edit, share and etc into buttons I don't know why I was thinking that it's a #(hash)

![img](https://www.dropbox.com/s/5g6a9iabk58fphp/Screenshot%202017-07-25%2011.22.41.png?dl=1)

**Comment by hackjutsu** [comment]
@Alaev 

Yes, the tag-style buttons were introduced because they were easy to implement so that I could focus on the core functionalities.
