### ISSUE TITLE
Acknowledge Evil icons in the setting panel (License section)

### ISSUE THREAD

**Issue by hackjutsu** [hackjutsu/Lepton#160]
Lepton uses [license-checker](https://github.com/davglass/license-checker) to automatically check for its dependencies' licenses, and lists them in the "Acknowledge" section below.

![jietu20170724-233059](https://user-images.githubusercontent.com/7756581/28558769-35fb753c-70c8-11e7-8684-e7c183216d05.jpg)

However, [Evil icons](http://evil-icons.io/)'s license (MIT) is not listed there because it's not installed as a npm package. 

A simple workaround would be to treat it as a special case in the code and push it to `LicenseList`.
https://github.com/hackjutsu/Lepton/blob/master/app/containers/settingPage/index.js#L13

Or append it into `LicenseInfo`.
https://github.com/hackjutsu/Lepton/blob/master/app/containers/settingPage/index.js#L14

**Comment by hackjutsu** [comment]
Maybe also update to use the latest [license-checker](https://www.npmjs.com/package/license-checker)?

**Comment by cixuuz** [comment]
what's the difference between above two options?

**Comment by hackjutsu** [comment]
@cixuuz The latest license-checker won't the issue, but its version happens to be outdated.

**Comment by cixuuz** [comment]
1. why not just install Evil icons as a package?
2. license-checker's latest release is v13.0.3. In package.json, "license-checker" is "^8.0.4".

**Comment by hackjutsu** [comment]
@cixuuz 

Partly because we only use a small subset of it. As far as I know, we embed the svg files directly.

You can simply update the version number to "^13.0.3".

_Sent from my OnePlus ONEPLUS A5000 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by cixuuz** [comment]
The acknowledge looks like the following, right?
Evil icons@1.9.0
License: MIT

**Comment by hackjutsu** [comment]
@cixuuz I believe so.
