### ISSUE TITLE
Show confirmation dialog before exit from editor by ESC

### ISSUE THREAD

**Issue by hackjutsu** [hackjutsu/Lepton#162]

**Comment by cixuuz** [comment]
The correct statement is that show confirmation if changed unsaved content in editor, and press ESC. 

Do you think a simple solution is to disable ESC in such situation?

**Comment by hackjutsu** [comment]
@cixuuz There are three options here:
1. Submit button to submit and close
2. Cancel button to cancel and close
3. ESC to cancel and close

I think users are clear about what they want when hitting (1)"Submit" and (3)"Cancel", but could accidentally hit (3)"ESC" without clear intention.  So we might just need to show the confirmation dialog for (3).

The challenging part is displaying a confirmation dialog on top of the editor dialog, and need to find a way to hide/disable the editor below.

**Comment by hackjutsu** [comment]
Code to launch to the Editor dialog(Modal). It looks like the "ESC to dismiss" is part of the Modal's features.

https://github.com/hackjutsu/Lepton/blob/master/app/containers/snippet/index.js#L289

**Comment by cixuuz** [comment]
The Modal is from react-bootstrap: https://react-bootstrap.github.io/components.html#modals

There is a prop: 
keyboard | boolean |   | Close the modal when escape key is pressed

I've tried to add this attribute in renderGistEditorModal. It disables ESCAPE in edit panel, but not in new gist (I guess this is controlled by another panel). So the best strategy is just to disable ESCAPE. 

1. I didn't find any solution to add a confirmation panel still. But is there possible to add another Model above the gist editor? Then we can control the behavior.

2. Using another set of shortcuts: https://electron.atom.io/docs/tutorial/keyboard-shortcuts/

**Comment by hackjutsu** [comment]
Thanks for research @cixuuz :)

You can find the new gist Modal here: https://github.com/hackjutsu/Lepton/blob/master/app/containers/userPanel/index.js

There is a `back-to-normal-mode` signal when the `ESC` is pressed.  It is used to return from "Immersive mode", but we can extend it to capture all `ESC` event for Modals. Once we catch it, we can then launch a confirmation Dialog for the exit.

https://github.com/hackjutsu/Lepton/blob/master/main.js#L155
https://github.com/hackjutsu/Lepton/blob/master/app/index.js#L590
