### ISSUE TITLE
Update Lepton to use Node 7 or 8

### ISSUE THREAD

**Issue by hackjutsu** [hackjutsu/Lepton#164]

**Comment by cixuuz** [comment]
I suppose to test node 7 first, then node 8. For each, which version should we test?

**Comment by hackjutsu** [comment]
@cixuuz 

Just tested with the latest version for 7 or 8. I would suggest using [nvs](https://github.com/jasongin/nvs) as node version management tool if you are running on Mac.

**Comment by cixuuz** [comment]
I'm using nvm. what's difference?

**Comment by hackjutsu** [comment]
@cixuuz Should be little to notice :)

**Comment by wezhang** [comment]
From Nodejs LTS schedule, 

8.x | Pending | Carbon | October 2017
-- | -- | -- | --

Only 2 months to get a stable LTS version.

**Comment by tecnyhn** [comment]
Ok. We can wait two months, and come back.

**Comment by cixuuz** [comment]
Ok. We can wait two months, and come back.

For above error, see this issue in node sass. I guess electron using its own node. Also, I find a tool that may help.

**Comment by hackjutsu** [comment]
@cixuuz I notice [node-sass](https://github.com/sass/node-sass) has supported node 8 already. Maybe we need to update it also.

>Supported Node.js versions 0.10, 0.12, 1, 2, 3, 4, 5, 6, 7 and 8.

**Comment by cixuuz** [comment]
It is weird that in npm, it is said support only to 7. https://github.com/hackjutsu/Lepton/issues/164

**Comment by hackjutsu** [comment]
@cixuuz Maybe the npm page is linked to its release branch. 
https://github.com/sass/node-sass/tree/release

**Comment by cixuuz** [comment]
Test successfully after upgrading new node sass. 

Test environment is Node 8.2.1. macOS Sierra. Node-sass 4.5.2.

The issue before was that node sass did not support node 8.
If any error like:

> Node Sass could not find a binding for your current environment: OS X 64-bit with Node.js 8.x

Please rebuild node-sass like

> npm

 rebuild node-sass

**Comment by Alaev** [comment]
its support 8 for a while now.
You can see here: [Link](https://github.com/sass/node-sass/releases)
Just be sure to run ```npm rebuild``` after node upgrade.
