### ISSUE TITLE
Update Lepton to use Webpack 3

### ISSUE THREAD

**Issue by hackjutsu** [hackjutsu/Lepton#165]

**Comment by cixuuz** [comment]
Current versions:
    "webpack": "^2.2.0",
    "webpack-node-externals": "^1.5.4"

Latest versions:
    "webpack": "^3.5.2",
    "webpack-node-externals": "^1.6.0"

**Comment by hackjutsu** [comment]
@cixuuz 

I expect it would just work after simply updating the version number. Unlike webpack 1 to webpack 2, there should be little breaking changes between 2 and 3.
