### ISSUE TITLE
Latest binary blocked by anti-virus

### ISSUE THREAD

**Issue by rubaboo** [hackjutsu/Lepton#166]
Symantec Endpoint Protection blocks Lepton-Setup-1.4.0-beta.exe.
Version 1.3 does not have this problem.
 In a corporate environment, I have no power to circumvent the "protection". So stuck with 1.3 for now.

**Comment by hackjutsu** [comment]
@rubaboo 

There is no code logics change between 1.4.0-beta and 1.3.0 except the GUI. I suspect the Symantec just simply doesn't like the word `beta` in the app name or manifest.

**Comment by rubaboo** [comment]
I understand it is most likely a false positive and has little to do with actual functionality. As far as I understand it, the antivirus picks up a pattern in the binary (`Lepton-Setup-1.4.0-beta.exe`) that it thinks is suspicious and is typically found in a virus. Note, it finds the pattern in the packaged installation file, not necessarily in your program.

**Comment by rubaboo** [comment]
I'm sure it has nothing to do with the word `beta`. But it can have something to do with the packaging tool you use to make the installer. Can you release the Windows binary in a "portable" format, i.e. without the installer, just unzip and run. Thanks.

**Comment by hackjutsu** [comment]
@rubaboo Thanks for investigation. I'll consider creating a 7z format for the next release.

**Comment by hackjutsu** [comment]
@rubaboo I have added a `.7z` format for 1.4.0 on Windows. Please check it out:)
