### ISSUE TITLE
New icon design?

### ISSUE THREAD

**Issue by hackjutsu** [hackjutsu/Lepton#168]
Recently, I have heard some advices on a new icon design. Unfortunately, I'm not good at drawing icons. 
![icon](https://user-images.githubusercontent.com/7756581/29088851-634b1214-7c2f-11e7-92da-1fb79b3896f1.png)

If you have any good idea, feel free to put it in the comment 💯

**Comment by Alaev** [comment]
Can't we use font awesome or other free to use icon library?

**Comment by hackjutsu** [comment]
@Alaev 

Yes, actually we are using [evil-icon](http://evil-icons.io/) in our next release. The issue is talking about the app icon:)

**Comment by Alaev** [comment]
Oh... I saw now the icon in the previous message.
what kind of theme overall style are you thing about? I can come up with some sketches

**Comment by wezhang** [comment]
Just kindly reminder, the spike of comma can't be seen in the small icon, looks like only a black point.

Refer to my desktop snapshot:

![image](https://user-images.githubusercontent.com/7385667/29110092-15f0ac38-7d18-11e7-855a-a62b786078ca.png)

![image](https://user-images.githubusercontent.com/7385667/29110199-6a789c0c-7d18-11e7-9cd6-8d1bc86ba923.png)

**Comment by cixuuz** [comment]
suggest remove shadow

**Comment by maskleo** [comment]
@hackjutsu    Is there any plan to add a theme? like `Sublime Text 2`.

**Comment by hackjutsu** [comment]
@maskleo I wish, but I'm not good at theme design.

**Comment by hackjutsu** [comment]
With the help of [Brandmark](http://brandmark.io/), the AI-based logo maker, I finally come out of something.

![lepton_color](https://user-images.githubusercontent.com/7756581/38006775-41ac988a-31fb-11e8-907f-a2e67c57a94b.png)
![lepton_inverse](https://user-images.githubusercontent.com/7756581/38006778-4397f216-31fb-11e8-814b-fc06421ee658.png)

**Comment by yihan-us** [comment]
Not sure if you are aware but this icon is really similar to atom editor.
![](https://cloud.githubusercontent.com/assets/72919/2874231/3af1db48-d3dd-11e3-98dc-6066f8bc766f.png)

**Comment by hackjutsu** [comment]
Most of early Electron-based apps are named after physics particles to show their origins like Atom, Photon. Lepton follows the naming convention intentionally at its very first beginning. So it’s not surprising to see these apps have similar icons.
