### ISSUE TITLE
Window not ending

### ISSUE THREAD

**Issue by rubinchyk** [hackjutsu/Lepton#170]
![img-2017-08-12-11-35-15](https://user-images.githubusercontent.com/3279356/29239254-10adbce2-7f53-11e7-8114-5152166b6594.png)

### How to implement: 
Markdown file consist some long code. This block increasing width of window.

**Comment by hackjutsu** [comment]
Might be the same issue here https://github.com/hackjutsu/Lepton/issues/126

**Comment by DNLHC** [comment]
pretty much sure i fixed this issue in new design release

**Comment by hackjutsu** [comment]
Thanks @DNLHC ：） 

@rubinchyk Please check out 1.4.0 and have a try. Hope this issue is resolved.
