### ISSUE TITLE
Scollbar leaves white space in snippet list

### ISSUE THREAD

**Issue by DNLHC** [hackjutsu/Lepton#172]
When the snippet panel cannot display all snippets scrollbar leaves white space
![](http://i.imgur.com/KD1DcEK.jpg)

**Comment by DNLHC** [comment]
@hackjutsu You probably missed it but i already pulled fix for this issue #174 , can you confirm that the issue is gone?

**Comment by hackjutsu** [comment]
@DNLHC Just checked. It's resolved :) I'll close this ticket.
