### ISSUE TITLE
Avoid auto update check in development environment

### ISSUE THREAD

**Issue by Gisonrg** [hackjutsu/Lepton#181]
Hi, thanks for this awesome product!

I tried to build it on my desktop, even though the app could start normally, I got this error:
```
Error: ENOENT, dev-app-update.yml not found
```
in the console. Google search leads me to [this issue](https://github.com/electron-userland/electron-builder/issues/1505) on electron-builder, and the suggestion from the discussion is to avoid doing auto update check in the dev environment.

Personally I felt it's meaningless to do the auto update check in development environment as well if we are creating the "latest" version 😛 )

We could try using the [electron-is-dev](https://github.com/sindresorhus/electron-is-dev) to do the environment check as they suggested.

**Comment by hackjutsu** [comment]
@Gisonrg 

Thanks for the suggestion :) Yes, it's meaningless to check for updates in a DEV environment. I'm OK with adopting the electron-is-dev package.

If you like, feel free to send a PR.

**Comment by Gisonrg** [comment]
Cool, I will submit a PR when I am free over the weekend 👍
