### ISSUE TITLE
Auto start

### ISSUE THREAD

**Issue by seza443** [hackjutsu/Lepton#184]
Hello

It would be really cool if Lepton could automatically start when I boot my computer.
It would avoid me to have to manually start it.

Best regards,
Tanguy

**Comment by hackjutsu** [comment]
I'm not a big fan to have an app automatically running. But I'll keep this ticket open and attach a reference post here. If someone feels this necessary and is willing to submit a PR, I love to get it merged.

https://github.com/electron-archive/grunt-electron-installer/issues/115

**Comment by seza443** [comment]
Yeah, I'm just lazy, I should configure my computer to start it automatically actually 😉
