### ISSUE TITLE
Match the style of markdown task list with Github style

### ISSUE THREAD

**Issue by Gisonrg** [hackjutsu/Lepton#195]
Follow up on #193

Currently, task list in Markdown is rendered as shown:
<img width="385" alt="screen shot 2017-08-23 at 12 42 20 am" src="https://user-images.githubusercontent.com/4332224/29576854-fb10420a-879b-11e7-9453-62a96d77f430.png">

It will be great if we could match the style of the list rendered by Github:

<img width="380" alt="screen shot 2017-08-23 at 12 50 22 am" src="https://user-images.githubusercontent.com/4332224/29577166-1486d13a-879d-11e7-8274-ef8e8414733d.png">

Each task list item rendered in the app has the class `.task-list-item`. We just need to define a new CSS rule to remove the bullet point in the list (or even make it look nicer).

**Comment by hackjutsu** [comment]
Just got some thought:  could we make the md style configurable? Like GitHub style, StackOverflow style.

**Comment by Gisonrg** [comment]
That would be a good enhancement but I am not sure if it will enhance the user experience.
Was busy these days so probably I'll update the list to match Github style first over the weekend 😃
