### ISSUE TITLE
Line numbers are taking 2 lines when >99

### ISSUE THREAD

**Issue by Offirmo** [hackjutsu/Lepton#196]
Line numbers are stuck to 2 char width, and wrap on 2 lines when >99
![screen shot 2017-08-25 at 14 52 57](https://user-images.githubusercontent.com/603503/29700113-54ca760c-89a5-11e7-8ef5-aa58961e8e12.png)

This also make the code interline big.

Ok snippets are rarely more than >99 lines, but that happens...

Btw Lepton is still awesome as ever

**Comment by hackjutsu** [comment]
@Offirmo 

What's your Lepton version? Can you share your gist so that I can reproduce on my side?

**Comment by hackjutsu** [comment]
@Offirmo Does the latest version get this issue resolved?

**Comment by Offirmo** [comment]
My Lepton was 1.4.0. 

Installing 1.4.1 doesn't solve the problem

Gist: https://gist.github.com/c9bcc9b0ea2b8e201e2c5c8723bdb2c9

**Comment by Offirmo** [comment]
The full screen:

![screen shot 2017-08-28 at 16 34 57](https://user-images.githubusercontent.com/603503/29761891-edd45e1a-8c0e-11e7-8321-ace6cbdce544.png)

**Comment by hackjutsu** [comment]
I cannot reproduce this issue on my Mac. The line number has a fixed width 40px, which should be able to show 3 digits (not sure about 4 digits). 

I suspect the app picks another font on your side, which makes 3-digit number exceeds 40px. Could you try opening the "Developer Tools" and increasing the width to 42px or above? If that works for you, I can put the fix on the coming release. (You can send a PR if you like.)

![jietu20170828-000942](https://user-images.githubusercontent.com/7756581/29762851-60cbd766-8b85-11e7-9e72-df2b71f106d3.jpg)

**Comment by Offirmo** [comment]
That's very strange, I have an up-to-date ordinary MacbookPro too.

Inspecting the CSS, I see ;
font-family: Consolas, "Liberation Mono", Menlo, Courier, monospace;

My setup has: 
* NO Consolas
* NO "Liberation Mono"
* YES Menlo
* NO Courier

Would your dev machine happen to have one of the 2 first fonts, hence explaining the different display?

**Comment by Offirmo** [comment]
Expanding to 42px works (not 41, though)

but couldn't that be made responsive ?

Ideas (didn't dive into them)
* https://stackoverflow.com/questions/7617689/make-table-width-100-with-last-column-filling-remainder-without-squashing-other
* https://stackoverflow.com/questions/8230777/how-do-i-set-the-table-cell-widths-to-minimum-except-last-column

**Comment by hackjutsu** [comment]
@Offirmo 

Thanks for your suggestions:)

Sometimes the fonts on OS could come with other packages/applications.

If `42px` would work (I hope it also works on Windows/Linux), I might like to stick to it since it keeps the code simple and maintainable.

**Comment by Offirmo** [comment]
I can totally understand the need for simplicity for personal projects, I'm struggling with mine, too ;)

**Comment by hackjutsu** [comment]
@Offirmo Would you like to send a PR or let me fix that?

**Comment by Offirmo** [comment]
new job, wifey = sorry, can't contribute more than issues :-P

**Comment by hackjutsu** [comment]
@Offirmo Understand:) I'll update this alpha release with the fix this weekend.

**Comment by hackjutsu** [comment]
@Offirmo Check out the latest Alpha release:)
