### ISSUE TITLE
[FR] search gist by gist id.

### ISSUE THREAD

**Issue by Cologler** [hackjutsu/Lepton#201]
Seems not supported yet.

**Comment by hackjutsu** [comment]
You are right. That's not supported yet.

I didn't come up with the scenario when users would search for the gist id. But since gist id is the unique identifier for a single gist, your request is legitimate:)

**Comment by hackjutsu** [comment]
https://github.com/hackjutsu/Lepton/releases/tag/1.4.1-alpha

Please check out the latest alpha release.
