### ISSUE TITLE
Visualization of ipynb files (Jupyter notebooks)

### ISSUE THREAD

**Issue by pierdom** [hackjutsu/Lepton#202]
Feature suggestion: visualization of Jupyter notebook files (ipynb, a json dialect) as it is currently done on Gist web front-end. Jupyter is a popular (almost the de-facto standard) tool for data exploration and crunching. Data science teams would absolutely benefit from a good integration in Lepton. 

The visualization it-self could be done through nbviewer.

**Comment by hackjutsu** [comment]
Thanks for the suggestions:)

Sample for .ipynb on gist.
https://gist.github.com/zonca/9fb017ad4a5587269067

**Comment by hackjutsu** [comment]
Working on a feature branch:
https://github.com/hackjutsu/Lepton/tree/feature/jupyternotebook-rendering

Here is a screenshot but need more testings.

<img width="1147" alt="jietu20180809-004723 2x" src="https://user-images.githubusercontent.com/7756581/43885749-9dfe2248-9b6e-11e8-9574-b43f5724addf.png">
