### ISSUE TITLE
Enhancing it for notes, articles etc., instead of code alone - other features

### ISSUE THREAD

**Issue by jkathir** [hackjutsu/Lepton#204]
Instead of making the editor has specific..Let it supports normal text as well without syntax highlighting..In the languages column  add english where it says C, C#....Please think of the following features to implement and it will be awesome..

1. Google like search engine like https://ambar.cloud/
2. Next, Previous, Go to Option like Folio Views
3. Number of hits found before hitting the actual search like Folio Views
4. Import options from Zim, Treepad or other wikis.
5. Handling huge number of documents by providing quick search via Solr or Apache Lucene
6. Support for tamil language
7. Having tags for each document (Reference: https://collatenotes.com/)
8. Built in web clipper (save webpages locally) - (Reference: https://collatenotes.com/)
9. Support for full text search in huge text nodes - example atleast 10,000 nodes with 100 kb of text each. Most note-taking software couldn't handle such huge content due to missing indexing
10. Quickest search results via indexing through Apache Lucene like docFetcher (http://www.techrepublic.com/blog/linux-and-open-source/portable-desktop-search-make-the-most-of-docfetcher/)

**Comment by hackjutsu** [comment]
@jkathir Thanks for your suggestions!

For 5, 9, 10, there are some limitations to build a full text search based on the GitHub APIs v3(https://github.com/hackjutsu/Lepton/issues/82).  Unless we host a server separately like collatenote, or GitHub decides to improve their APIs, I don't expect this feature soon.

I haven't dived into the details for the rest. I'll put my thoughts here once I've done that.

**Comment by hackjutsu** [comment]
I would like Lepton to be focused on a lean gist client/snippet manager other than a universal note taking app. 

So I'll close this issue. Thank for suggestions :)
