### ISSUE TITLE
download issue

### ISSUE THREAD

**Issue by hismayilov** [hackjutsu/Lepton#205]
Dear all,

I have 20bps of internet, normally I don't have any issue wile downloading any file, but Lepton is very slow.
sometimes it shows 5-7 hour, and than drops. is there any issue on download links?
could you please provide any mirror.

**Comment by hismayilov** [comment]
<img width="425" alt="screen shot 2017-09-08 at 2 18 16 pm" src="https://user-images.githubusercontent.com/676555/30207472-aef210d0-94a0-11e7-8df5-896b9df94390.png">

**Comment by hackjutsu** [comment]
I suspect it has something to do with your network connection with the GitHub resource servers. Maybe the CDN (if any) hasn't propagate the binaries to your area.

**Comment by hismayilov** [comment]
I have tried different ISPs and succeeded 👍 thank you.
