### ISSUE TITLE
Dark theme

### ISSUE THREAD

**Issue by ArLEquiN64** [hackjutsu/Lepton#206]
I want dark theme like white character and black background.
and if you don't mind, could you support any syntax theme?

**Comment by hackjutsu** [comment]
@ArLEquiN64 
What kind of dark them are you referring to ?
- app
- editor
- syntax highlight

**Comment by hackjutsu** [comment]
I would like to keep the current [Ando Theme](https://en.wikipedia.org/wiki/Tadao_Ando) for Lepton.

**Comment by hackjutsu** [comment]
Does someone know how to load CSS dynamically in webpack?

**Comment by DNLHC** [comment]
@hackjutsu you could use dynamic import
```javascript
if (darkTheme) {
}
```

**Comment by hackjutsu** [comment]
Thanks @DNLHC 

I created a feature branch https://github.com/hackjutsu/Lepton/tree/feature/dark-theme, but run into error
```
ERROR in ./app/containers/loginPage/index.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
SyntaxError: 'import' and 'export' may only appear at the top level (12:2)

  10 | const darkTheme = true
  11 | if (darkTheme) {
> 12 |   import './index.scss'
     |   ^
  13 | } else {
  14 |   import './index.dark.scss'
  15 | }
```

**Comment by DNLHC** [comment]
@hackjutsu Yeah, the [dynamic import](https://webpack.js.org/api/module-methods/#import-) has slightly different syntax to the static one, it should be called with parenthesis.

**Comment by vielhuber** [comment]
Some update on this?

**Comment by vviikk** [comment]
This looks like a good project I can work on this week. I'll keep you guys posted.

**Comment by hackjutsu** [comment]
@vviikk Feel free to take a look at the feature/dark-theme branch.

**Comment by vviikk** [comment]
Hi, @hackjutsu. Could we communicate on Spectrum? I've created a room there. Currently, I'm updating outdated dependencies as I had a bit of trouble getting it to work locally (in Linux & WSL). IIRC, last month I was also having build issues on the Mac. Once I get to build with the latest toolchain, I'll make a PR.

Would like to pick your brain about styled-components & it's theme layer and slowly moving out of Bootstrap.

[![Join the community on Spectrum](https://withspectrum.github.io/badge/badge.svg)](https://spectrum.chat/Lepton)

**Comment by Jamdx** [comment]
When this feature will be part of it? dark mode!!

**Comment by hackjutsu** [comment]
<img width="996" alt="Screen Shot 2019-04-28 at 9 14 32 PM" src="https://user-images.githubusercontent.com/7756581/56876209-b15e5280-69fa-11e9-873e-c6309bd13ac4.png">

Working an early version of dark mode based in [feature/dark-theme](https://github.com/hackjutsu/Lepton/tree/feature/dark-theme) branch. It takes some time to tune the colors here and there. Stay tuned.

**Comment by vielhuber** [comment]
Wow, awesome!
