### ISSUE TITLE
full-text search

### ISSUE THREAD

**Issue by glody** [hackjutsu/Lepton#208]
full-text search is very important, do you have plan to support this? thanks.

gistbox and gisto all support this function

**Comment by hackjutsu** [comment]
Thanks for the suggestions. As discussed in https://github.com/hackjutsu/Lepton/issues/82, the content search across all gists is not well supported by GitHub API.

To overcome it, we have to either host a server like Gistbox, or only provide content search to those gists that have been downloaded before like Gisto. (Correct me if I'm wrong.)

I think GistBox would be a better alternative if full-text search is critical in your case:)
