### ISSUE TITLE
I wish this could have Black Theme

### ISSUE THREAD

**Issue by doray10000** [hackjutsu/Lepton#209]
I wish this could have Black Theme, Thanks this software is so good . It is easy to search and manage my gists.

**Comment by doray10000** [comment]
editor would be fine if ever or something like 

![image](https://user-images.githubusercontent.com/3487018/30521270-94995468-9bef-11e7-8f1f-841ccc594204.png)

**Comment by hackjutsu** [comment]
Thanks! We already have an issue for that https://github.com/hackjutsu/Lepton/issues/206.
