### ISSUE TITLE
Tags containing spaces, dots, hyphens?

### ISSUE THREAD

**Issue by JPGygax68** [hackjutsu/Lepton#211]
Are such tags possible? If so, how ?

**Comment by hackjutsu** [comment]
@JPGygax68 

As discussed in https://github.com/hackjutsu/Lepton/issues/200, the Twitter tags parser doesn't allow this. But fortunately, there is another hidden tags parsing algorithm there:
```
[title] description #tags: tag1, tag2, tag2
```
In this case, tags are separated by comma. But remember, `#tags: tag1, tag2` will take precedence over`#tag1 #tag2`, so you can use them together. Here is an example:

https://gist.github.com/59394ed0a53eaca871eae7022d250c10

**Comment by JPGygax68** [comment]
Thank you @hackjutsu, `#tags:` is working perfectly. Perhaps a future version can feature a UI element for this?

**Comment by hackjutsu** [comment]
@JPGygax68 Good suggestion. I'll keep it in mind:)
