### ISSUE TITLE
Configuring proxy on windows

### ISSUE THREAD

**Issue by nico2610** [hackjutsu/Lepton#215]
Hello, 

Is there an option to configure proxy for Windows installation ?

Thanks

**Comment by hackjutsu** [comment]
The "Home" directory varies on different Windows platform. I find `C:\Users\<CurrentUserName>` works for me on Win10. You can try placing a `.leptonrc` there with your proxy configs.

https://stackoverflow.com/a/42966089/3697757

**Comment by nico2610** [comment]
It's the same on Win7. Thanx
