### ISSUE TITLE
latex support in markdown

### ISSUE THREAD

**Issue by shelper** [hackjutsu/Lepton#216]
for the sake of math...

**Comment by hackjutsu** [comment]
@shelper Thanks for the suggestion:)

I don't use latex myself. Can you give me an example of the expected rendering and the actual rendering? A sample gist would be helpful:)

**Comment by shelper** [comment]
for example, as shown in the image below
i was told mathjax is the most popular tool/plugin for such rendering, hope this helps, 

thanks


<img width="969" alt="screen shot 2017-09-24 at 4 01 24 pm" src="https://user-images.githubusercontent.com/546163/30786300-b7119648-a141-11e7-93f4-c70ac716789c.png">

**Comment by hackjutsu** [comment]
https://www.npmjs.com/package/markdown-it-mathjax
https://github.com/hackjutsu/Lepton/blob/master/app/utilities/markdown/index.js#L13

**Comment by hackjutsu** [comment]
<img width="1006" alt="jietu20180404-202806 2x" src="https://user-images.githubusercontent.com/7756581/38345962-ec25b034-3846-11e8-8979-85fe10827b05.png">
