### ISSUE TITLE
Can not login to github in Ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by kovtunos** [hackjutsu/Lepton#217]
I can not log in to Github with Lepton. After entering my credentials and pressing Log In, the app just shows login screen with progress bar.

This what shown in logs. No errors.

```
2017-09-24T10:37:45.014Z - info: [Dispatch] updateAuthWindowStatus ON
2017-09-24T10:38:07.869Z - info: [Dispatch] updateAuthWindowStatus OFF
2017-09-24T10:38:07.877Z - info: [Dispatch] updateUserSession IN_PROGRESS
2017-09-24T10:38:08.918Z - info: [Dispatch] updateAccessToken
```

After several attempts I logged in only once and after restart there is the same login progress bar.
Tried this on two separate Ubuntu 16.04 LTS x64 machines with different graphical environments. The result is the same.

I have 3 Electron apps on my machines, all of them have no problems.

p.s. Node v. 8.5.0

**Comment by hackjutsu** [comment]
@kovtunos Thanks for testing. Could you have a try for 1.4.3-alpha?
https://github.com/hackjutsu/Lepton/releases/tag/1.4.3-alpha

**Comment by kovtunos** [comment]
I tried this version as well.
