### ISSUE TITLE
Unable to edit an existing long gist and save it.

### ISSUE THREAD

**Issue by willemdh** [hackjutsu/Lepton#219]
I seem unable to edit a long gist and save it. When I scroll down, it stops before I can reach the submit button.

**Comment by hackjutsu** [comment]
@willemdh I haven't met such a long gist before. If you don't mind, can you share such long gist so that we can have a test on it?

**Comment by willemdh** [comment]
Well the gist really doesn't have to be that long, take for example https://gist.github.com/53d0bd7c524190da15865fcf65a476bf

So in Lepton, I click the edit pencil, click in the name textfield, then click in the content text block, scroll down, but I'm not able to see the submit button.

**Comment by hackjutsu** [comment]
![jietu20170926-091459](https://user-images.githubusercontent.com/7756581/30871316-4766009e-a29b-11e7-8fd7-e2490835c4cd.jpg)

Which platform are you testing on? Just tested on macOS, and it works.

**Comment by hackjutsu** [comment]
@willemdh Unfortunately I don't have a win7 machine for testing... I'll keep this open in case I can reproduce it on other machines.

**Comment by willemdh** [comment]
Ok, my guess is that in about 6 months my employer will allow me to update to Windows 10. I'll make sure to test again then. It's a minor bug anyway, I know how to workaround it now.
