### ISSUE TITLE
Blank page for users without gists... 

### ISSUE THREAD

**Issue by BitTigerDashBoardAgent** [hackjutsu/Lepton#22]
This looks pale... We can show some dummy stuff.

![image](https://cloud.githubusercontent.com/assets/18759677/22171927/9bf3f7bc-df4e-11e6-8414-39ccc02033df.png)

**Comment by hackjutsu** [comment]
fixed:https://github.com/hackjutsu/Lepton/commit/59e41f69db5a60ec38a8bbe85bc30e75091da36e
