### ISSUE TITLE
Use own git

### ISSUE THREAD

**Issue by Fastidious** [hackjutsu/Lepton#222]
I love the app. How difficult would it be to make it GitHub agnostic? It would be great if it could be made, so it simply uses a git repository, without having to rely on GitHub.

**Comment by hackjutsu** [comment]
All GitHub specific APIs have been extracted to this file:
https://github.com/hackjutsu/Lepton/blob/master/app/utilities/githubApi/index.js

If your own servers can provide compatible methods, feel free to have a try.

**Comment by Fastidious** [comment]
@hackjutsu those are custom APIs for GitHub. They don't exist on a git repository. This is what I was envisioning:

- A "gists" git repository is created by the app using user's credentials for user's own git server.
- Gists are stored on the "gists" git repository.
- App read/writes on the repository, presenting gists as it does now.

I know the idea means changing the entire functionality of the app revolving around GitHub gists. It is a radical change, and not the direction you might want --or know how to-- take.

**Comment by hackjutsu** [comment]
@Fastidious 

Sorry, I just realized that you are talking about using a general Git repository for storage. Yes, this is an interesting idea. There would be a challenge about where to put the meta data, like descriptions. GitHub Gist provides an abstraction layer which bundles the gists and the description together.  Without this support, we need to invent our own "gist id" which bundle the actual gist file and description file. IMHO, I doubt we can do this better than the existing solution.

**Comment by Algram** [comment]
Will this be implemented at some point in the future? I would really like that option, so we could use it for sensitive data that can't be stored on GitHub.
