### ISSUE TITLE
Feature Request: Remember which section in the side panel is expanded

### ISSUE THREAD

**Issue by sanderman123** [hackjutsu/Lepton#224]
I always search through my gists by tag. Right now I have to re-expand the tags section in the side panel all the time. Lepton won't remember which section I had expanded last time and always defaults to a state with all sections half open, which is kind of annoying.

**Comment by hackjutsu** [comment]
Thanks for reporting. This can easily implemented because Lepton already has its mechanism to remember the pinned tags. 

If you (or anyone is interested), you can try tracing this line to see how it works out.
https://github.com/hackjutsu/Lepton/blob/master/app/index.js#L59

**Comment by sanderman123** [comment]
I think I was misunderstood, or I don't understand how the pinned tags work haha. 
But what I mean is that all sections in the side bar (LANGUAGES, PINNED and TAGS) can be expanded by clicking on them. However, when you restart Lepton, the app forgets which section you had expanded.
I never navigate my gists by using LANGUAGES or PINNED, so I always want the TAGS section expanded and the rest minimized.

**Comment by hackjutsu** [comment]
The pinned tag section is for pinning your frequently used tags on the left, so that you don't need to expand or scroll to find your tag. If you have a lot of tags like me, you'll find it pretty helpful.

**Comment by hackjutsu** [comment]
Have a try for 1.4.3-alpha-7 :)

**Comment by sanderman123** [comment]
Awesome, it works in alpha-7! Thanks!
