### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by dare023** [hackjutsu/Lepton#228]
Hi, must say I like your app, but I would like to ask:
1. Can the app be permanently logged in? After every reboot, I need to log in again. (Arch Linux x64, latest Lepton) 
2. I saw that there are requests for the color scheme, if that is complicated can you just increase the weight and set some darker color of the font? It's very thin and quite unreadable.
I am referring to the font in the code window, ofc.
3. Can Search be placed on top of gist list, so when searched list can be filtered?

Thank you for great app in any case.

**Comment by hackjutsu** [comment]
> 1. Can the app be permanently logged in? After every reboot, I need to log in again. (Arch Linux x64, latest Lepton)

Just need to cache token somewhere that won't be cleared after the reboot.

> 2. I saw that there are requests for the color scheme, if that is complicated can you just increase the weight and set some darker color of the font? It's very thin and quite unreadable.
I am referring to the font in the code window, ofc.

PR is welcome :)

> 3. Can Search be placed on top of gist list, so when searched list can be filtered?

I personally like Alfred style search bar and might plan to explore on it. If you find placing the search bar on the top of the gist list is critical in your case, PR is welcome :) We can place a flag to switch between different styles.
