### ISSUE TITLE
Login window spinning on Windows 10 with v1.5 x64 

### ISSUE THREAD

**Issue by girishrau** [hackjutsu/Lepton#231]
The more we know about your system and use case, the more easily and likely we can help.

#### Environment info
Running Lepton v1.5.0 _x64 portable on Windows 10
Launched Lepton, supplied Github credentials. Login just keeps spinning.
[2017-10-12T20.06.00.782Z.log](https://github.com/hackjutsu/Lepton/files/1380537/2017-10-12T20.06.00.782Z.log)

**Comment by girishrau** [comment]
I behind a corporate proxy server. If that is causing the time out, how do I configure the proxy?

**Comment by hackjutsu** [comment]
There is a default timeout 10s for each REST call.  Please refer to the [Wiki](https://github.com/hackjutsu/Lepton/wiki/Proxy) for proxy support.
