### ISSUE TITLE
Add syntax highlighting

### ISSUE THREAD

**Issue by balmungsama** [hackjutsu/Lepton#232]
The more we know about your system and use case, the more easily and likely we can help.

#### Environment info
* OS: Windows 10
* App Version (`Command/Ctrl + ,`): 1.5.0

#### If possible, provide the log files
- Mac: `~/Library/Application Support/Lepton/logs`
- Windows: `C:\Users\<username>\AppData\Roaming\Lepton\logs`
- Linux: `~/.cached/Lepton/logs`
>The [debug mode](https://github.com/hackjutsu/Lepton/wiki) is recommended when producing the logs. 
>You can send your log file to cosmo.lepton@gmail.com if don't want to post it here.

**Comment by hackjutsu** [comment]
Sorry, but what's your issue exactly?

**Comment by balmungsama** [comment]
Oh, this isn't an issue. More of a feature request.

Best,
John.
On 2017-10-17 6:03:13 PM, CosmoX <notifications@github.com> wrote:
Sorry, but what's your issue exactly?

**Comment by hackjutsu** [comment]
@balmungsama 

Not sure I understand correctly. Lepton provides syntax highlighting for both the snippets and the editor. Could you specify which language highlighting is missing? It would be best if there is a screenshot or sample gist. 😃

**Comment by hackjutsu** [comment]
Feel free to reopen this issue if there is a better clarification for the feature request.

**Comment by balmungsama** [comment]
Sorry, I meant syntax highlighting _themes_. I prefer using Tomorrow Night Bright for all of my code editors and managers when possible.
