### ISSUE TITLE
Feature request: UI / UX improvements, Searching and Sorting

### ISSUE THREAD

**Issue by MBurvill** [hackjutsu/Lepton#233]
#### Environment info
* OS: Win 10
* App Version:  Lepton v1.5.0

#### Feature request
First impressions of Lepton having previously used snippets app and then gistbox I immediately missed these features:
**Sorting:** Sort by created, and sort by modified
**Searching:** Permanent search bar in UI

**Comment by hackjutsu** [comment]
>Sorting: Sort by created, and sort by modified

To be honest, I don't quite know why these sortings are useful. However, the gists are already sorted by the updated date anyway ... 

>Searching: Permanent search bar in UI

I prefer the Alfred style search bar. A personal taste.
