### ISSUE TITLE
Add a preference to configure close window just hide to background?

### ISSUE THREAD

**Issue by twiceyuan** [hackjutsu/Lepton#235]
The more we know about your system and use case, the more easily and likely we can help.

#### Environment info
* OS: macOS 10.13
* App Version (`Command/Ctrl + ,`): Lepton v1.5.0

#### Description of the problem / feature request / question:
Hope to add a preference to configure close window just hide to background. Because that is normal logic in most of application on macOS. After close window use Cmd+W must restart completely will be slowly.

**Comment by hackjutsu** [comment]
Thanks for the suggestion! This is a pretty interesting point:)

**Comment by hackjutsu** [comment]
https://github.com/electron/electron/blob/master/docs/api/browser-window.md#winhide

**Comment by hackjutsu** [comment]
@twiceyuan Please have a try for [v1.5.1-alpha-4](https://github.com/hackjutsu/Lepton/releases/tag/v1.5.1-alpha).

**Comment by twiceyuan** [comment]
It works, thank you for your effort. 👍🏼
