### ISSUE TITLE
Very long lines make right-side buttons inaccessible

### ISSUE THREAD

**Issue by goodevilgenius** [hackjutsu/Lepton#236]
The more we know about your system and use case, the more easily and likely we can help.

#### Environment info
* OS: macOS and Linux (probably Windows too)
* App Version: 1.5.0

#### Description of the problem / feature request / question:

When viewing a gist with very long lines, the buttons on the right side become inaccessible.

They can be accessed via keyboard (hitting Tab enough times).

#### If possible, provide a sample gist or screenshot:

<https://gist.github.com/goodevilgenius/5548330>

![image](https://user-images.githubusercontent.com/254662/32058292-3deedbd4-ba2f-11e7-98fe-cdba16cbdd0f.png)

After tabbing to the buttons:

![image](https://user-images.githubusercontent.com/254662/32058483-b46ea122-ba2f-11e7-8f97-cb7648a579a6.png)

**Comment by hackjutsu** [comment]
@goodevilgenius I have to admit, you are a genius on testing.

**Comment by DNLHC** [comment]
fixed 04da7b6
