### ISSUE TITLE
Use the gist title as the snippet default title instead of the description

### ISSUE THREAD

**Issue by raphaelfeng** [hackjutsu/Lepton#238]
Currently, the title of the snippet is the description of the gist, need to manually put the title as [title] to change the title.
gist title is the name of the first file in the gist, so can we use that in [title] by default?

**Comment by hackjutsu** [comment]
Thanks for the suggestions:)

There are some concernings about using the first file name as the gist title. 

1. The files in a gist are sorted alphabetically. It's hard to know which file is the "main" file.
2. Some users might end up with a bunch of gists with titles like "index.js", "test.java" and "example.cpp"...

Taken this into consideration, using the description as the title is more informative. Feel free to put your thoughts here :)

**Comment by raphaelfeng** [comment]
Maybe add an option to choose option or the first file name?

The main file seems to be the first file after sorting them alphabetically.

**Comment by hackjutsu** [comment]
@raphaelfeng 

The `.leptonrc` file provides different configuration options. If you are interested, just have a look at https://github.com/hackjutsu/Lepton/commit/5902b3b53cb90e5a395b42e4820a8b605611ffaf, which add the option to make new gist private.
