### ISSUE TITLE
After it finally loads (10+ seconds on an i7), Lepton will not login

### ISSUE THREAD

**Issue by vaderj** [hackjutsu/Lepton#239]
https://imgur.com/a/h9XDj

The more we know about your system and use case, the more easily and likely we can help.

#### Environment info
* OS: Win10/x64
* App Version (`Command/Ctrl + ,`):  UNKNOWN - latest.  Unable to open the About dialog since it wont even login

#### Description of the problem / feature request / question:
Login?
Start faster than MSWord opening a 1GB file over a phoneline?

#### If possible, provide a sample gist or screenshot:
https://imgur.com/a/h9XDj

#### If possible, provide the log files
- Mac: `~/Library/Application Support/Lepton/logs`
- Windows: `C:\Users\<username>\AppData\Roaming\Lepton\logs`
- Linux: `~/.cached/Lepton/logs`
>The [debug mode](https://github.com/hackjutsu/Lepton/wiki) is recommended when producing the logs. 
>You can send your log file to cosmo.lepton@gmail.com if don't want to post it here.

**Comment by hackjutsu** [comment]
The loading bar is just an animation. The login could fail due to network or other issues. Please forward the logs so that we can investigate on that.

>Start faster than MSWord opening a 1GB file over a phoneline?
If you wish to pay and afford me to hire a professional team with thousands of developers, then the answer is YES.

**Comment by hackjutsu** [comment]
This seems to be the same issue as https://github.com/hackjutsu/Lepton/issues/234.
