### ISSUE TITLE
Sync failure if the profile image caching fails

### ISSUE THREAD

**Issue by hackjutsu** [hackjutsu/Lepton#246]
The app should be tolerant of this minor issue, other than rejecting the login.

Related issues:
- https://github.com/hackjutsu/Lepton/issues/245
- https://github.com/hackjutsu/Lepton/issues/241
- https://github.com/hackjutsu/Lepton/issues/234

**Comment by cixuuz** [comment]
It should be fixed by treating an insignificant warning not as a fatal error when failing to cache the profile image. Here is the code https://github.com/hackjutsu/Lepton/blob/dd9551d647914ab55adeb967804adad7ac12edae/app/index.js#L420, right?

**Comment by hackjutsu** [comment]
@cixuuz Maybe the issue comes from this if condition.
https://github.com/hackjutsu/Lepton/blob/master/app/index.js#L419
