### ISSUE TITLE
Unable to log in with GitHub Desktop client present

### ISSUE THREAD

**Issue by rrozitis** [hackjutsu/Lepton#248]
The more we know about your system and use case, the more easily and likely we can help.

#### Environment info
* OS: Win10 Enterprise (1607)

#### Description of the problem:
Unable to log in. I suspect this has something to do with the fact I have the GitHub Desktop client running on the same machine and in that one I'm logged into our enterprise GitHub server while Lepton attempts to log into the public GitHub. (this is just a suspicion though).

#### Logs
Logs sent to cosmo.lepton@gmail.com. Sent the Lepton logs from today + Fiddler capture from the login attempt

**Comment by hackjutsu** [comment]
Try delete C:\Users\<username>\AppData\Roaming\Lepton\ .

**Comment by rrozitis** [comment]
That did it!
