### ISSUE TITLE
Unable log in during second start

### ISSUE THREAD

**Issue by LiVanych** [hackjutsu/Lepton#249]
#### Environment info
* OS: Ubuntu 16.04(LTS)
* App Version:  Lepton-1.5.0-x86_64.AppImage

#### Description of the problem / feature request / question:
Problem with second running this tools. Unable to log in.

./Lepton-1.5.0-x86_64.AppImage
installed: X-AppImage-BuildId=e5e1c080-ae55-11a7-10ab-2561df3f8314 image: X-AppImage-BuildId=e5e1c080-ae55-11a7-10ab-2561df3f8314
info: 

----- Lepton v1.5.0 -----

info: [signal] sending auto-login signal
info: [Dispatch] updateAccessToken
init: 2945.452ms
info: [Dispatch] updateSyncTime
info: [Dispatch] updateGists
info: [Dispatch] updateGistTags
info: [Dispatch] fetchSingleGist 3a09ef4478d23011204acd0b03ef8cc3
info: [Dispatch] selectGist 3a09ef4478d23011204acd0b03ef8cc3
info: [Dispatch] updatePinnedTags
error: The request has failed: 
{}
info: [Dispatch] updateUserSession INACTIVE
info: The app window is closed

**Comment by hackjutsu** [comment]
Try delete  ~/.cached/Lepton/

**Comment by LiVanych** [comment]
It has other path in my system: ~/.config/Lepton
Why it's happened? If it no secret...
Thank you!

**Comment by amirmishani** [comment]
Having this same issue in Mac with the exact log when I run the app. And I don't see any Lepton cache folder anywhere on my system to delete.

**Comment by hackjutsu** [comment]
@LiVanych  Lepton calls `app.getPath('userData')` to access a folder for caching user data. It uses whatever path the OS returns, which varies depends on the platform.
