### ISSUE TITLE
win10-64,login fail

### ISSUE THREAD

**Issue by maskleo** [hackjutsu/Lepton#251]
version : `Lepton-1.5.1-alpha-1-win.7z`
- fill right username and password ,dialog show `sync successd`.
- click `login button`,dialog show `sync fail`.

Previous successful login and complete operation.

This is error log.
[2017-12-21T02.16.18.329Z.log](https://github.com/hackjutsu/Lepton/files/1577673/2017-12-21T02.16.18.329Z.log)

**Comment by maskleo** [comment]
I can't visit https://gist.github.com/.
but I can visit https://github.com.

**Comment by hackjutsu** [comment]
This is a known bug reported here https://github.com/hackjutsu/Lepton/issues/246.
Try delete C:\Users\<username>\AppData\Roaming\Lepton\

**Comment by maskleo** [comment]
OK,It working now.Thanks.
This is a great tool.
I like it.
