### ISSUE TITLE
[question] gists is blocked,Why Lepton can linkd.

### ISSUE THREAD

**Issue by maskleo** [hackjutsu/Lepton#258]
Q1: `https://gist.github.com/` is blocked,Why `Lepton` can linkd.
Q2: Is there an IOS App Development Plan?
Q3:  I hope `Lepton` can show and be copied  `<script src="https://gist.github.com/XXX/xxxx.js"> 
 </script>  `  I think u know what I mean.
Thanks.

**Comment by hackjutsu** [comment]
@maskleo Thanks for giving Lepton a try:)

Q1: `https://gist.github.com/` is blocked,Why Lepton can linkd.
A: Sorry, I have no idea. Lepton simply follows GitHub v3 API guidance to consume GitHub Gist service. You might have to look into how `https://gist.github.com/` is blocked.

Q2: Is there an IOS App Development Plan?
A: No on my side. But PR is welcome.

Q3: I hope Lepton can show and be copied <script src="https://gist.github.com/XXX/xxxx.js"> </script> I think u know what I mean.
A: I guess you want more share options. This feature request might be what you mean. https://github.com/hackjutsu/Lepton/issues/114

**Comment by maskleo** [comment]
@hackjutsu Thanks for your reply.
