### ISSUE TITLE
Feature request: Display the list of files in a Gist

### ISSUE THREAD

**Issue by robl2e** [hackjutsu/Lepton#260]
#### Environment info
* OS:
* App Version (`Command/Ctrl + ,`):

#### Description of the problem / feature request / question:

It would be great if there was a way to display the list of files that are in a Gist. For my use case, I have a single Gist with several files. It would make navigation easier if I can see the list of files and be able to view/edit them by selecting from a the list.

#### If possible, provide the log files
- Mac: `~/Library/Application Support/Lepton/logs`
- Windows: `C:\Users\<username>\AppData\Roaming\Lepton\logs`
- Linux: `~/.cached/Lepton/logs`
>The [debug mode](https://github.com/hackjutsu/Lepton/wiki) is recommended when producing the logs. 
>You can send your log file to cosmo.lepton@gmail.com if don't want to post it here.

**Comment by hackjutsu** [comment]
Try creating `.leptonrc` at your home directory, and set the field `snippet.expanded` to be `false`.

You can refer this [gist](https://gist.github.com/hackjutsu/1ad7e4968eb64d881ec9dedd6c0f400b) for more details.

**Comment by robl2e** [comment]
Thanks! That does help, but it doesn't resolve the issue completely in my use case. Changing `snippet.expanded` to false does allow me to better see the overall view of files. 

However, if I choose a file and want to edit it, the edit window would just bring me to the beginning of the gist and I would still need to scroll to the file I want to edit. Is there another setting/option that can help here? Or some way to perform an inline edit?

**Comment by hackjutsu** [comment]
@robl2e 

Thanks for having a try:) Inline editing requires some significant refactoring which I don't expect it happening in the near future. If you are interested, feel free to send a PR;)

**Comment by robl2e** [comment]
No problem :) I did notice clicking the "#raw" on the listed file seems to bring up some kind of edit window for the file but there's no way to save. So there does seem to be a "place" where this functionality could be added, but sounds like it's not trivial to do so. 

I would like to contribute if I could, but I'm a mobile dev, so my web/JS skills would be lacking ;)
