### ISSUE TITLE
Syntax hightlight issue for FSharp file ( .fs , .fsx )

### ISSUE THREAD

**Issue by callmekohei** [hackjutsu/Lepton#263]
#### Environment info
```
~$ sw_vers 
ProductName:	Mac OS X
ProductVersion:	10.13.3
BuildVersion:	17D47

~$ brew info lepton
lepton: stable 1.2.1 (bottled), HEAD
Tool and file format for losslessly compressing JPEGs
https://github.com/dropbox/lepton
Not installed
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/lepton.rb
==> Dependencies
Build: cmake ✔
==> Options
--HEAD
	Install HEAD version
```

#### Description of the problem / feature request / question:

Syntax hightlight issue for FSharp file ( .fs , .fsx )

#### If possible, provide a sample gist or screenshot:
![screen shot 2018-02-10 at 18 55 05](https://user-images.githubusercontent.com/17691683/36060829-3b9bce32-0e94-11e8-995e-e4aacb975820.png)

#### If possible, provide the log files
- Mac: `~/Library/Application Support/Lepton/logs`
- Windows: `C:\Users\<username>\AppData\Roaming\Lepton\logs`
- Linux: `~/.cached/Lepton/logs`
>The [debug mode](https://github.com/hackjutsu/Lepton/wiki) is recommended when producing the logs. 
>You can send your log file to cosmo.lepton@gmail.com if don't want to post it here.

**Comment by hackjutsu** [comment]
@callmekohei Thanks for reporting!

Lepton uses [highlight.js](https://github.com/isagalaev/highlight.js) for syntax highlight. If you find a language support is missing, that might be a better place for a request 😃

**Comment by callmekohei** [comment]
@hackjutsu 

Thank you for your reply! (^_^)/

https://github.com/isagalaev/highlight.js/issues/1704

**Comment by hackjutsu** [comment]
@callmekohei Thanks! Feel free to reopen this ticket once the language support is added.

**Comment by gusbemacbe** [comment]
@callmekohei and @hackjutsu,

That original author of highlight.js is no longer online since August 2017.

I am not contributor, but I'll try to add a new F# syntax highlighting.

Pygments, written in Python, has F# syntax highlighting.
