### ISSUE TITLE
OAuth flow results in 404 from github

### ISSUE THREAD

**Issue by cpdean** [hackjutsu/Lepton#265]
#### Environment info
* OS: osx
* App Version (`Command/Ctrl + ,`): `npm install && npm run build && npm run start` on master ( 6288a86ba6a674122a8100a2dc3f04d0de063088 )

#### Description of the problem / feature request / question:
When clicking the Github Login button on startup, I get sent to a github 404 web page.  When I open up the inspector on the page, I think it's on the correct url:

![image](https://user-images.githubusercontent.com/160099/36437295-93300fbc-1634-11e8-8ce4-58754eadd19c.png)

I can't verify if this is wrong or not, but according to the [oauth docs](https://developer.github.com/apps/building-oauth-apps/authorization-options-for-oauth-apps/) they mention using this url to begin the flow:

```
GET https://github.com/login/oauth/authorize
```

Which is what Lepton appears to be doing.  When I visit that url in a browser, I get the same 404, so maybe this is really a bug on Github: https://github.com/login/oauth/authorize

![image](https://user-images.githubusercontent.com/160099/36437487-1f3789c2-1635-11e8-8f0e-00ddd466e86c.png)

Where should this get reported, or how do I further debug this?

**Comment by hackjutsu** [comment]
@cpdean 

Did you try the release binary or build from the source? For the latter, you need to register the app on GitHub and provide the client id and secret. Please refer to the "Client ID/Secret" section of the README.

**Comment by cpdean** [comment]
oh interesting, yeah i didn't do the full registration.

How do i put in urls for an electron app?

![image](https://user-images.githubusercontent.com/160099/36856876-1ecbf11e-1d45-11e8-934b-b5e812d1cdf9.png)

**Comment by hackjutsu** [comment]
AFAIK, it doesn't matter what is the home page URL.  For the callback URL, it's a URL that the login page will be redirected to with an appended auth code. 

This is a general OAuth app registration procedure. The Electron app uses an embedded webview(Chromium) to fetch the auth code from the redirected page(where the callback URL points to), so there is no difference between a web app and an Electron app here.  Ideally, each registration should have their own callback URL.

You can learn more about the GitHub OAuth process [here](https://developer.github.com/apps/building-oauth-apps/authorization-options-for-oauth-apps/).

**Comment by cpdean** [comment]
Awesome, I registered an app for building and testing Lepton from source, i just used `https://example.com/` for both urls and it worked fine.

Thanks!

**Comment by hackjutsu** [comment]
Feel free to play with the code. If you find something interesting, don't hesitate to send a PR:)
