### ISSUE TITLE
Tags search exactly

### ISSUE THREAD

**Issue by rl4debug** [hackjutsu/Lepton#266]
How can we search exactly tags in Lepton?

For example: i have 2 tags: java, javascript

I want to get all snip of java, so i will search java, but the result includes javascript too

**Comment by hackjutsu** [comment]
Not sure I understand your request correctly, do you mean the "and", "or" logic for the search keywords? For example, "java & javascript" for results matching "java" and "javascript" at the same time, and "java | javascript" for results matching either of the keywords?

**Comment by rl4debug** [comment]
for example, i have only 2 snippets:
1. `[title1] description1 #java`
2. `[title1] description1 #javascript`

When i type `#java` in searching input, the result includes 2 snippets.
That is not my expected result.
I wonder if tags searching work correctly?

**Comment by hackjutsu** [comment]
@rl4debug Lepton uses [fuse.js](http://fusejs.io/) for fuzzy search. There is a parameter `threshold` to decide from a perfect match to a fuzzy match.  This parameter is exposed yet. If you are interested, I can point you the code.

**Comment by rl4debug** [comment]
I mean, `javascript` contains `java`, so i can't search only `java` tag. Can you help me.
