### ISSUE TITLE
是否可以设置默认选中private呢？

### ISSUE THREAD

**Issue by heavenzone** [hackjutsu/Lepton#267]
使用过很多基于markdown的跨平台云笔记软件，cmd markdown,  为知笔记等，cmd markdown对文档管理比较差，为知笔记的markdown编辑器太鸡肋，最近也尝试使用lepton，发现真的很好用，跨平台，云同步，文档索引方面如果可以设置一级分类、二级分类就更好了，最后问一下是否可以设置默认选中private呢？

**Comment by little-tomorrow** [comment]
可以使用配置文件 .leptonrc 去设置默认选中 private，https://gist.github.com/hackjutsu/1ad7e4968eb64d881ec9dedd6c0f400b

**Comment by heavenzone** [comment]
gist被墙，没弄科学上网，看到不到链接-_-!

**Comment by little-tomorrow** [comment]
![链接截图](https://user-images.githubusercontent.com/23186480/36785611-5f818c46-1cbe-11e8-964d-bd9f548e9acc.png)

**Comment by heavenzone** [comment]
非常感谢，设置成功！

**Comment by hackjutsu** [comment]
@little-tomorrow Thanks!
