### ISSUE TITLE
/ in filename fails silently without error.

### ISSUE THREAD

**Issue by pratham2003** [hackjutsu/Lepton#268]
The more we know about your system and use case, the more easily and likely we can help.

#### Environment info
* OS: Windows
* App Version (`Command/Ctrl + ,`): v1.5.1

#### Description of the problem / feature request / question:
/ in the filename prevents it from working.

#### If possible, provide a sample gist or screenshot:
https://i.imgur.com/JShyAgY.png

#### If possible, provide the log files
https://hastebin.com/sotizacome.scala

**Comment by hackjutsu** [comment]
‘/‘ is not considered as a valid token for a file name. Maybe we should add validation for each file name before submitting to the Gist sever.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
