### ISSUE TITLE
win10 install error

### ISSUE THREAD

**Issue by wjx0912** [hackjutsu/Lepton#270]
The more we know about your system and use case, the more easily and likely we can help.

#### Environment info
* OS: win10 (1709)
* App Version (`Command/Ctrl + ,`):Lepton.Setup.1.5.2-alpha-2.exe

#### Description of the problem / feature request / question:
i run Lepton.Setup.1.5.2-alpha-2.exe,  and no gui display, in windows event manager i found error:
[http://23.83.237.60/1.png](http://23.83.237.60/1.png)
[http://23.83.237.60/2.png](http://23.83.237.60/2.png)

i test another windows7, it works well, have compatibility for win10?
thanks.

**Comment by hackjutsu** [comment]
AFAIK, there is no compatibility issue for win10 so far. What about having a try for `Lepton-1.5.1-win.7z`?

**Comment by wjx0912** [comment]
hi, hackjutsu , 
thanks for your reply, i have test Lepton-1.5.1-win.7z, it works normal.
