### ISSUE TITLE
Ctrl+F short key to search in gist item?

### ISSUE THREAD

**Issue by hoangweb** [hackjutsu/Lepton#274]
i wish you add short key: ctrl+F to search entire in gist item inside Lepton window. This feature like google chrome (ctrl+F)

**Comment by hackjutsu** [comment]
Do you mean searching gists based on content, or just searching texts within the visible window? 

Reference:
- https://github.com/electron/electron/issues/2037

**Comment by hoangweb** [comment]
yes, https://github.com/rhysd/electron-in-page-search extractly what i need. SO how to install it in lepton?
second question:
How to search gist in tag scope?

**Comment by hackjutsu** [comment]
You might need to modify the code to integrate the "Ctrl + F" feature.

Gist search in tag scope is not supported. Currently, Lepton uses simple fuzzy search provided by [fusejs](http://fusejs.io/). But it's not hard to implement this feature. If you are interested, you can simply filter the search result based on specific tags. The relevant logic can be found here https://github.com/hackjutsu/Lepton/blob/dev/app/utilities/search/index.js.

Let me know if you want to play with the source code and need more details for the bootstrap.

**Comment by hoangweb** [comment]
If i can't install with lepton, please tell me if you upgrade Lepton.

**Comment by stidch** [comment]
It's a more Mac related question:
Does anybody know how to create a MacOS global shortcut (like shift+f), which automatically starts Lepton and opens the search dialog in the Application?
