### ISSUE TITLE
Changes are not taken when putting a "/" character in the filename

### ISSUE THREAD

**Issue by romainnorberg** [hackjutsu/Lepton#275]
#### Environment info
* OS: MacOs Sierra 10.12.6 (16G1212)
* App Version (`Command/Ctrl + ,`): v1.6.0

#### Description of the problem / feature request / question:
Changes are not taken when putting a "/" character in the filename (see gif), no error message is provided.
Github doesn't allow /' in the name

#### If possible, provide a sample gist or screenshot:
![recordIt](http://g.recordit.co/DRy1ouCEbM.gif)

**Comment by hackjutsu** [comment]
It's not a valid token for a filename in most OSs, maybe we need a warning for that. To be honest, I don't know why users would try this...

**Comment by romainnorberg** [comment]
users often do mistake like this

**Comment by hackjutsu** [comment]
FYI, `cmd + e` is the shortcut for editing an existing gist.

**Comment by hackjutsu** [comment]
Reference package: https://www.npmjs.com/package/valid-filename
