### ISSUE TITLE
Add an option to have a normal sized scroll bar?

### ISSUE THREAD

**Issue by jbaranski** [hackjutsu/Lepton#287]
The more we know about your system and use case, the more easily and likely we can help.

#### Environment info
* OS: Windows 10
* App Version (`Command/Ctrl + ,`): Lepton v1.5.1

#### Description of the problem / feature request / question:
The scrollbar is extremely tiny and hard to see and click, an option so the scrollbar doesn't have any styling would be great

#### If possible, provide a sample gist or screenshot:
![image](https://user-images.githubusercontent.com/10889950/38772691-f0dd118c-400a-11e8-988b-0260b8cb06ae.png)

#### If possible, provide the log files
- Mac: `~/Library/Application Support/Lepton/logs`
- Windows: `C:\Users\<username>\AppData\Roaming\Lepton\logs`
- Linux: `~/.cached/Lepton/logs`
>The [debug mode](https://github.com/hackjutsu/Lepton/wiki) is recommended when producing the logs. 
>You can send your log file to cosmo.lepton@gmail.com if don't want to post it here.

**Comment by hackjutsu** [comment]
Thank you for your suggestion! We'll keep improving Lepton's usability in the future design :)

**Comment by skywind3000** [comment]
It is 2019, can we have the scroll bar now ?? I believe a big part of Lepton users are using Windows not macOS. Hiding the scrollbar on windows is very unefficient.
