### ISSUE TITLE
Can't get through to the UI after login when there is a gist without description

### ISSUE THREAD

**Issue by dukewan** [hackjutsu/Lepton#29]
![wechatimg30](https://cloud.githubusercontent.com/assets/2100515/22312354/470857ae-e30c-11e6-9564-ecfc8cd2bd0d.jpeg)

**Comment by hackjutsu** [comment]
fixed:https://github.com/hackjutsu/Lepton/commit/f4f0b77daabe1c967508955a0ee1b50179daf32e
