### ISSUE TITLE
Lepton doesn't have an application icon

### ISSUE THREAD

**Issue by dserodio** [hackjutsu/Lepton#295]
The more we know about your system and use case, the more easily and likely we can help.

#### Environment info
* OS: Linux (Ubuntu 18.04) 
* App Version (`Command/Ctrl + ,`): v1.6.2

#### Description of the problem / feature request / question:

Lepton doesn't have an application icon. I installed it from https://github.com/hackjutsu/Lepton/releases/download/v1.6.2/Lepton-1.6.2-x86_64.AppImage

#### If possible, provide a sample gist or screenshot:

![Screenshot](https://i.imgur.com/nHthR0R.png)

#### If possible, provide the log files
- Mac: `~/Library/Application Support/Lepton/logs`
- Windows: `C:\Users\<username>\AppData\Roaming\Lepton\logs`
- Linux: `~/.cached/Lepton/logs`
>The [debug mode](https://github.com/hackjutsu/Lepton/wiki) is recommended when producing the logs. 
>You can send your log file to cosmo.lepton@gmail.com if don't want to post it here.

 `~/.cached/Lepton/logs` doesn't exist, and the link to [debug mode](https://github.com/hackjutsu/Lepton/wiki) in the issue reporting template doesn't work.

**Comment by hackjutsu** [comment]
Thanks for reporting. I noticed this bug intermittently but don't have a good idea to fix it yet.

**Comment by hackjutsu** [comment]
https://github.com/electron-userland/electron-builder/issues/2269

**Comment by hackjutsu** [comment]
https://github.com/hackjutsu/Lepton/commit/c3a14248b0688957a54d6f616691b29cf51caf69

**Comment by kuang-da** [comment]
I just met the same issue after downloading 1.9.1 appImage
https://github.com/hackjutsu/Lepton/releases/download/v1.9.1/Lepton-1.9.1.AppImage
