### ISSUE TITLE
Zoom In vs. Font size

### ISSUE THREAD

**Issue by DaemonPhenex** [hackjutsu/Lepton#303]
Purely aesthetic issue.
• I want to keep the navigation panel a certain size but increase the font size of the text viewer.
Perhaps resizing panels on mouse hover.
### Extra
I'm new to gist and looking for a better means of organizing snippets then the hierarchical windows explorer but I was wondering if there's a limit to private gists? considering the private checkbox is blanked.
Edit: Under the impression, it's an issue on gist side cause it seems I can't make a gist private after it's been created, forcing you to make a new one should you forget to check the box. Unless I don't know how this works, would be nice if they added this.

• Would be nice to have the option to collapse files by default.
• I know there's already an open issue #206 regarding dark theme but another vote in favor!

Compared to boostnote and cacher this is a great alternative, thanks for your work 🙂.

**Comment by hackjutsu** [comment]
Hey @DaemonPhoenix42, thanks for your suggestion! 

A quick answer to file collapsing. We can configure the `.leptonrc` to make the snippet files collapsed by default. (We can also make snippet private by default.)
https://gist.github.com/hackjutsu/1ad7e4968eb64d881ec9dedd6c0f400b#file-leptonrc-L3

**Comment by DaemonPhoenix42** [comment]
Thank you, seems "newSnippetPrivate": true, is working fine but "expanded": false, isn't responding accordingly.

**Comment by hackjutsu** [comment]
Which version do you test with?

**Comment by DaemonPhoenix42** [comment]
hmm... idk how I ended up with - Lepton v1.6.3-beta.2 
but all is good in - Lepton v1.6.3-beta.3
<3
