### ISSUE TITLE
Aesthetic Enhancement - Visual Basic Syntax Highlights

### ISSUE THREAD

**Issue by DaemonPhoenix42** [hackjutsu/Lepton#304]
Within the editor .vbs files have the appropriate syntax highlights but it seems it doesn't appear in the file viewer.

![vbssyntax](https://user-images.githubusercontent.com/36192863/44066075-3e5d37a8-9f23-11e8-983d-ca1490c454e9.PNG)

Here is my gist so you can use it for testing if it helps.
https://gist.github.com/DaemonPhoenix42/cd775d69c3542ee0de4679a3b1f46553

Just adds a toggle for hidden files to the context menu for easier access because I disabled the Explorer ribbon.

The first file is a .reg, I believe gist doesn't have support for registry files so I sent a request for it (idk if it will go through, I'm unaware of any reasons i.e. security implications perhaps for lack of support). I changed it to .txt because otherwise it gets marked as "#Other" in the language tab.

**Comment by hackjutsu** [comment]
Thanks @meilinz !
