### ISSUE TITLE
Batch Syntax Highlights

### ISSUE THREAD

**Issue by DaemonPhenex** [hackjutsu/Lepton#306]
Syntax Highlights for .bat not present
Lepton v1.7.0

**Comment by hackjutsu** [comment]
Thanks for reporting! Can you share a sample gist so that we can test against?

**Comment by DaemonPhoenix42** [comment]
No problem and thank you. My apologies for the wait. If you still need a gist here you are!
https://gist.github.com/DaemonPhoenix42/93662a5cde4066999d31cc20040c79dc
Highlights seem to be present on the official Gist page.

**Comment by hackjutsu** [comment]
We try to match Gist online editor but not always possible. Maybe we can try the hybrid syntax highlighting of highlightJS and [PrismJS](https://prismjs.com/).

**Comment by hackjutsu** [comment]
https://github.com/hackjutsu/Lepton/commit/6420f917b2a58eeafb09327afe0d439458a00271
