### ISSUE TITLE
1.7.0 markdown codeblock isn't supported

### ISSUE THREAD

**Issue by accn94** [hackjutsu/Lepton#307]
The more we know about your system and use case, the more easily and likely we can help.

#### Environment info
* OS: osx 10.13.3
* App Version (`Command/Ctrl + ,`): 1.7.0

#### Description of the problem / feature request / question:
1.7.0 markdown codeblock isn't supported

#### If possible, provide a sample gist or screenshot:
[1.6.2]
<img width="307" alt="2018-08-20_07-45-57" src="https://user-images.githubusercontent.com/17037446/44313992-40b76d00-a44d-11e8-843a-51126c9c7848.png">

[1.7.0]
<img width="245" alt="2018-08-20_07-44-55" src="https://user-images.githubusercontent.com/17037446/44313982-2087ae00-a44d-11e8-8839-1a0fc158dde3.png">

#### If possible, provide the log files
- Mac: `~/Library/Application Support/Lepton/logs`
- Windows: `C:\Users\<username>\AppData\Roaming\Lepton\logs`
- Linux: `~/.cached/Lepton/logs`
>The [debug mode](https://github.com/hackjutsu/Lepton/wiki) is recommended when producing the logs. 
>You can send your log file to cosmo.lepton@gmail.com if don't want to post it here.

**Comment by hackjutsu** [comment]
Fixed the markdown code block styling issue in https://github.com/hackjutsu/Lepton/commit/d791102e328c16f52608737c9e6d0a7c42f88247.
