### ISSUE TITLE
Save a single snippet file locally

### ISSUE THREAD

**Issue by hackjutsu** [hackjutsu/Lepton#308]
https://github.com/electron/electron/blob/master/docs/api/dialog.md#dialogshowsavedialogbrowserwindow-options-callback

**Comment by infosisio** [comment]
@hackjutsu Please add local filesystem support, we want our computing sovereignty.

**Comment by hackjutsu** [comment]
@infosisio Thanks for the suggestion:) Adding a local db/fileSys is a non-trivial change which I don't have a plan for the near future. But I'm more than happy to provide a code tour for those who would like to work on a PR. This issue is only about saving a snippet to the local system as a separate file.

**Comment by infosisio** [comment]
@hackjutsu I understand that but it's a pity for such a nice project and a bit peculiar for the motto to be "democratization of snippets" and yet we are locked to Github servers.
