### ISSUE TITLE
Unable to run lepton on Ubuntu 18.04 on amd ryzen system.

### ISSUE THREAD

**Issue by NikhilSaini38** [hackjutsu/Lepton#310]
The more we know about your system and use case, the more easily and likely we can help.

#### Environment info
* OS: Ubuntu 18.04
* App Version : any

#### Description of the problem / feature request / question:
Unable to run lepton, reason being that my kernel is not working with snapd. I cannot downgrade my kernel else my ubuntu wont work. Suggest some way to get stable build.

#### If possible, provide the log files
- Mac: `~/Library/Application Support/Lepton/logs`
- Windows: `C:\Users\<username>\AppData\Roaming\Lepton\logs`
- Linux: `~/.cached/Lepton/logs`
>The [debug mode](https://github.com/hackjutsu/Lepton/wiki) is recommended when producing the logs. 
>You can send your log file to cosmo.lepton@gmail.com if don't want to post it here.

**Comment by hackjutsu** [comment]
@NikhilSaini38 If the snap package doesn't work in your case, you can try AppImage. Download the latest release from here https://github.com/hackjutsu/Lepton/releases/tag/v1.7.0.
