### ISSUE TITLE
License is listed as proprietary on Ubuntu store

### ISSUE THREAD

**Issue by kfazz** [hackjutsu/Lepton#313]
In the Ubuntu store app Lepton's license shows as 'proprietary'
on the store website license shows as 'unset'
https://snapcraft.io/lepton

**Comment by cosmo1024** [comment]
I don't how to update the license on the store. Please use the GitHub
license as the single source of truth.

**Comment by hackjutsu** [comment]
I tried and can not figure out how to update the UI. Please use GitHub license as the single source of true. Thanks.
