### ISSUE TITLE
Update README with how to configure Github enterprise

### ISSUE THREAD

**Issue by StephenGregory** [hackjutsu/Lepton#317]
#### Environment info
* OS: MacOS 10.12.6
* App Version: 1.7.0

#### Description of the problem / feature request / question:

After installing via `brew cask`, the UI does not give an option. I can't seem to find where a config file would be located. How do I do?

**Comment by gargolito** [comment]
> #### Environment info
> * OS: MacOS 10.12.6
> * App Version: 1.7.0
> 
> #### Description of the problem / feature request / question:
> After installing via `brew cask`, the UI does not give an option. I can't seem to find where a config file would be located. How do I do?

Where you able to get this to work? It doesn't look like lepton is even reading my ~/.leptonrc (MacOS)

**Comment by StephenGregory** [comment]
Yes. My configuration is in the same location as yours.

```
{
    "snippet": {
        "expanded": true,
        "newSnippetPrivate": false,
        "sorting": "updated_at", 
        "sortingReverse": true
    },
    "editor" : {
        "tabSize": 4
    },
    "userPanel": {
        "hideProfilePhoto": false
    },
    "logger": {
        "level": "debug"
    },
    "enterprise": {
        "enable": true,
        "host": "your.host.com",
        "token": "your-token"
    }
}

```
