### ISSUE TITLE
Support for collapsible markdown

### ISSUE THREAD

**Issue by vielhuber** [hackjutsu/Lepton#323]
Hello!

I use this technique a lot: https://gist.github.com/joyrexus/16041f2426450e73f5df9391f7f7ae5f

<details><summary>For example here!</summary>
<p>

#### yes, even hidden code blocks!

```php
phpinfo();
```

</p>
</details>

Unfortunately leptons gist viewer does not support that.

Are there any plans of adding it?

**Comment by hackjutsu** [comment]
Thanks for the suggestion! Lepton use [markdown-it](https://github.com/markdown-it/markdown-it) for markdown rendering which has a plugin system. Let me know if there is any plugin would support this feature. I'm more than happy to integrate it.

**Comment by vielhuber** [comment]
Unfortunately they do not plan to add it: https://github.com/markdown-it/markdown-it/issues/510#issuecomment-434395177

So this can be closed?
