### ISSUE TITLE
[feature request] macOS Mojave (10.14) dark mode support

### ISSUE THREAD

**Issue by singularitti** [hackjutsu/Lepton#326]
#### Environment info
* OS: macOS 10.14.1 (18B75)
* App Version (`Command/Ctrl + ,`): 1.7.0

#### Description of the problem / feature request / question:
The macOS 10.14 (Mojave) has supported a new ["dark mode"](https://developer.apple.com/design/human-interface-guidelines/macos/visual-design/dark-mode/), which renders the app's titlebar, settings panel, etc., all to a "vibrant dark" color. Will Lepton.app support this? Thank you!

#### If possible, provide a sample gist or screenshot:
<img width="728" alt="light mode and dark mode" src="https://user-images.githubusercontent.com/25192197/47976984-a6e28200-e083-11e8-8684-bad83379b6b2.png">

**Comment by vviikk** [comment]
Let's track this on #206. I think we can close this for now.
