### ISSUE TITLE
Login fail [page not found]

### ISSUE THREAD

**Issue by DeadNumbers** [hackjutsu/Lepton#328]
#### Environment info
* OS: Arch Linux
* App Version: v1.7.0

![_2018-11-17_13-27-08](https://user-images.githubusercontent.com/9416005/48660057-9521b700-ea53-11e8-964e-31ab4c0843e9.png)

**Comment by hackjutsu** [comment]
Are you building from your local machine? Or download from released page?

**Comment by DeadNumbers** [comment]
@hackjutsu build from localhost

**Comment by hackjutsu** [comment]
@DeadNumbers Did you enter the client id and client secret as described in the readme? https://github.com/hackjutsu/Lepton#client-idsecret

**Comment by DeadNumbers** [comment]
@hackjutsu I'm added client id and client secret to `/opt/lepton-snippet-manager/configs/account.js` after build. it is not right? need to create a `config.js` before build package?

**Comment by hackjutsu** [comment]
yes, before build

**Comment by DeadNumbers** [comment]
@hackjutsu thanks, thats work good :+1:
