### ISSUE TITLE
Please update the snap version to support .ipynb file, it's still 1.6.2

### ISSUE THREAD

**Issue by WuShichao** [hackjutsu/Lepton#334]
#### Environment info
* OS: Linux Mint 19
* App Version (`Command/Ctrl + ,`): snap version, 1.6.2

#### Description of the problem / feature request / question:
Please update the snap version to support .ipynb file, it's still 1.6.2: https://snapcraft.io/lepton

#### If possible, provide a sample gist or screenshot:

![image](https://user-images.githubusercontent.com/6574526/50383926-6a80e900-06f8-11e9-9bcb-77d912684a64.png)

**Comment by hackjutsu** [comment]
Thanks, I’ll update snap store for the new Lepton version. Stay tuned!

**Comment by hackjutsu** [comment]
https://snapcraft.io/lepton updated to 1.7.3
