### ISSUE TITLE
GitHub login not working

### ISSUE THREAD

**Issue by cristianciofu** [hackjutsu/Lepton#340]
#### Environment info
* OS: macOS 10.14.2
* App Version (`Command/Ctrl + ,`): v1.7.0

#### Description of the problem / feature request / question:
After logging in to GitHub, I see the autorisation page, but the button is disabled. I had to manually enable it from the console in order to continue.

#### If possible, provide a sample gist or screenshot:
![image](https://user-images.githubusercontent.com/2684268/52531172-a0fadd80-2d11-11e9-9f11-e0ea5a642e65.png)

#### If possible, provide the log files
<img width="798" alt="capture d ecran 2019-02-10 a 08 59 56" src="https://user-images.githubusercontent.com/2684268/52531256-c2a89480-2d12-11e9-8772-cf7944d26565.png">

**Comment by lfalck** [comment]
Hi!

I am getting the same behaviour on Windows.

#### Environment info

* OS: Windows 10 Pro 1803
 * App Version: v1.7.0

#### If possible, provide a sample gist or screenshot:
![image](https://user-images.githubusercontent.com/30367604/52539382-db01c900-2d7d-11e9-8202-3ff3aeee7bf7.png)

#### If possible, provide the log files
[2019-02-10T20.42.10.378Z.log](https://github.com/hackjutsu/Lepton/files/2849388/2019-02-10T20.42.10.378Z.log)

**Comment by hackjutsu** [comment]
Thanks for reporting! It sounds like we have to upgrade the Electron version which should contain a newer Chromium version.

**Comment by wizarot** [comment]
I have the same problem.

**Comment by markdon** [comment]
I worked around this, then looked up an issue. Sorry I don't have a screenshot.

- Get to the 'Authorize Lepton' page in the screenshot above. 
- Open the Dev Tools (CTRL-Shift-i)
- Type window.location.href into the console, copy the URL.
- Open the URL in another browser and continue.
- Close the 'Authorize application' window and click 'Login with GitHub' again.
- You should be in.

**Comment by hackjutsu** [comment]
Sorry for this inconvenience. The master has the latest Electron which should resolve this issue. Unfortunately I just traded in my previous macbook and waiting for the new one to arrive... Should be able to release a new version at the end of Feb. Before that, pls follow markdon’s steps to work around this.

**Comment by rslhdyt** [comment]
thank you @markdon for your solution 👍

**Comment by RealSlimMahdi** [comment]
> I worked around this, then looked up an issue. Sorry I don't have a screenshot.
> 
> * Get to the 'Authorize Lepton' page in the screenshot above.
> * Open the Dev Tools (CTRL-Shift-i)
> * Type window.location.href into the console, copy the URL.
> * Open the URL in another browser and continue.
> * Close the 'Authorize application' window and click 'Login with GitHub' again.
> * You should be in.

CMD+opt+i for macos Users

**Comment by hackjutsu** [comment]
Please have a try for the latest release! Thanks for @cixuuz for updating the Electron version! 
https://github.com/hackjutsu/Lepton/releases/tag/v1.7.3

**Comment by lfalck** [comment]
1.7.3 works on Windows, thanks!
