### ISSUE TITLE
Overlay not working for scrollbar

### ISSUE THREAD

**Issue by hackjutsu** [hackjutsu/Lepton#342]
#### Environment info
* OS: macOS 10.14.3
* App Version (`Command/Ctrl + ,`): 1.7.3

#### Description of the problem / feature request / question:
The scrollbar in the middle panel should be overlaid over the list other than taking a port of a verticl e space.

#### If possible, provide a sample gist or screenshot:
<img width="998" alt="screen shot 2019-03-02 at 10 55 39 am" src="https://user-images.githubusercontent.com/7756581/53686291-138c2700-3cda-11e9-8995-fc95d4de57f4.png">

**Comment by sujin2f** [comment]
I will fix this issue for warming up.
