### ISSUE TITLE
v1.7.3 - no valid code signature

### ISSUE THREAD

**Issue by dalDevelo** [hackjutsu/Lepton#343]
The more we know about your system and use case, the more easily and likely we can help.

#### Environment info
* OS: macOS
* App Version: 1.7.3

#### Description of the problem / feature request / question:
Little snitch no longer lets Lepton connect to GitHub (based on my previous LS rules, which worked fine) because there is an issue with the applications code signature.

#### If possible, provide a sample gist or screenshot:
![ls screenshot](https://user-images.githubusercontent.com/44850778/53688299-fedf7b80-3d39-11e9-9eea-9cca211e8706.png)

#### If possible, provide the log files
- Mac: `~/Library/Application Support/Lepton/logs`
- Windows: `C:\Users\<username>\AppData\Roaming\Lepton\logs`
- Linux: `~/.cached/Lepton/logs`
>The [debug mode](https://github.com/hackjutsu/Lepton/wiki) is recommended when producing the logs. 
>You can send your log file to cosmo.lepton@gmail.com if don't want to post it here.

**Comment by hackjutsu** [comment]
Thanks for the quick report! Yes, I didn't continue my Apple developer account this year. Pls let me know if there is any feature broken without a code sign.
