### ISSUE TITLE
Can we have a option to toggle showing avatar?

### ISSUE THREAD

**Issue by haolin29** [hackjutsu/Lepton#345]
The more we know about your system and use case, the more easily and likely we can help.

#### Environment info
* OS: Mac
* App Version (`Command/Ctrl + ,`): Lepton v1.7.1

#### Description of the problem / feature request / question:
Feature request: Option to toggle avatar showing

**Comment by hackjutsu** [comment]
We can hide the avatar by configuring the `.leptonrc`.
https://gist.github.com/hackjutsu/1ad7e4968eb64d881ec9dedd6c0f400b#file-leptonrc-L11-L13
