### ISSUE TITLE
I create lepton.json on scoop,Now it can install lepton with a line command on Windows

### ISSUE THREAD

**Issue by akkuman** [hackjutsu/Lepton#347]
I pushed a json for lepton on [https://github.com/lukesampson/scoop-extras](https://github.com/lukesampson/scoop-extras) 
Now we can install Lepton with a line command on windows.
More Details can be viewed on [https://scoop.sh/](https://scoop.sh/) or [https://github.com/lukesampson/scoop](https://github.com/lukesampson/scoop)

**Comment by hackjutsu** [comment]
That's cool! Thank you!
