### ISSUE TITLE
Sharing button?

### ISSUE THREAD

**Issue by hackjutsu** [hackjutsu/Lepton#35]
What benefit will it provide if there is a sharing button?
- How
  - Email (Gmail)
  - Embedded link
- Content
  - Plain text/ Rich text
  - Gist link

**Comment by hackjutsu** [comment]
I don't see a point for the sharing button. Users can easily copy&paste the snippet to their IM or email.

**Comment by tmr232** [comment]
That said, a "copy gist link" button would be nice.

**Comment by hackjutsu** [comment]
@tmr232 I can reopen it if it deserves a discussion.

**Comment by hackjutsu** [comment]
Share options:

- GitHub Gist link
- website embedded link
- plain text
- html tag
- pdf

**Comment by tmr232** [comment]
Personally, my preferred way to share this would be a gist link. I spent a while searching the UI to make sure there was no such option.

**Comment by hackjutsu** [comment]
@tmr232 Sorry. Yes, it a gist link is useful.

**Comment by hackjutsu** [comment]
@tmr232 Something like this?

![amgdi2sdll](https://cloud.githubusercontent.com/assets/7756581/22679983/89573c4e-ecba-11e6-97bb-d67152d2a1a4.gif)

**Comment by tmr232** [comment]
This looks great!
Haven't had time to test it though (changed some files for the Enterprise integration, so I need to build it myself).
