### ISSUE TITLE
snippets|php.json invalid filename

### ISSUE THREAD

**Issue by jericopulvera** [hackjutsu/Lepton#351]
#### Environment info
* OS: MacOS Mojave
* App Version (`Command/Ctrl + ,`): 1.7.3

#### Description of the problem / feature request / question:
I used settings sync extension in vscode and it creates snippets|php.json file now when I'm editing it using this app it causes an invalid filename error.

**Comment by hackjutsu** [comment]
It would be helpful if we have some relevant logs.

**Comment by jericopulvera** [comment]
@hackjutsu I'm not sure where to get the relevant log. I opened the devtools and click save edit but no logs appeared on devtools. 

Here is the screenshot.
![Screen Shot 2019-04-21 at 9 29 53 AM](https://user-images.githubusercontent.com/23246308/56464273-45875300-6418-11e9-9667-2db6b1098b93.png)

**Comment by hackjutsu** [comment]
Now we can disable the filename validation in .leptonrc configurations. https://github.com/hackjutsu/Lepton/pull/421
