### ISSUE TITLE
Darkmode example

### ISSUE THREAD

**Issue by newzero** [hackjutsu/Lepton#353]
First, GREAT Software, thank you for your work.
But I really wanted a Darkmode for Lepton, so I made one.
Based on Monokai colorsheme

Because I'm new to this whole GitHub/Electron stuff, I made a fork and added my changes there, if you/anyone want to use it I'd be happy (only CSS changes of course)
https://github.com/newzero/Lepton
(Preview Screenshot added to Readme)

Also uploaded a custom build for direct use, but only Windows Version (sorry Linux/Mac users)
Earlier or later there might be a Darkmode in the official Version, until then this could be an alternative. Thx again

**Comment by hackjutsu** [comment]
@newzero Thanks for working on this! I'll take a look and keep you updated.

**Comment by Jamdx** [comment]
Please make it happen!

**Comment by hackjutsu** [comment]
https://github.com/hackjutsu/Lepton/issues/206

**Comment by hackjutsu** [comment]
The dark mode will be available in the next release. Stay tuned:)
