### ISSUE TITLE
Can I customize my favorite keyboard shortcuts?

### ISSUE THREAD

**Issue by godhelpjun** [hackjutsu/Lepton#356]
The more we know about your system and use case, the more easily and likely we can help.

#### Environment info
* OS:windows 10
* App Version (`Command/Ctrl + ,`):1.73

#### Description of the problem / feature request / question:
ctrl + esc  opens windows "start" menu, does not work as expecting closing editor

#### If possible, provide the log files
- Mac: `~/Library/Application Support/Lepton/logs`
- Windows: `C:\Users\<username>\AppData\Roaming\Lepton\logs`
- Linux: `~/.cached/Lepton/logs`
>The [debug mode](https://github.com/hackjutsu/Lepton/wiki) is recommended when producing the logs. 
>You can send your log file to cosmo.lepton@gmail.com if don't want to post it here.

**Comment by rijnhard** [comment]
I too would like to customise my hotkeys.
Primarily to make it match up with what I have setup on IntelliJ and Atom

**Comment by jessycormier** [comment]
+1 having the ability to match other IDE tools (vs code?) CTRL+SHIFT+P for a command pallet is my go to in apps without thinking now so having the ability to bring search or something up that's meaningful would be fantastic 👍

**Comment by hackjutsu** [comment]
I don't have a plan for it in the near future, but feel free to play with the code and send PRs if you have good solutions. A straightforward way is the add these customization in `.leptonrc` config.

https://github.com/hackjutsu/Lepton/blob/master/main.js#L40-L48
