### ISSUE TITLE
Will there be a iOS/Android version?

### ISSUE THREAD

**Issue by Kyle-Ye** [hackjutsu/Lepton#360]
#### Description of the problem / feature request / question:

Will there be a iOS/Android version so that we can view our gists in a "Lepton"'s way(an organised way)? 
I know there is already some app that can display the github'gists but they are all based on github raw gists.THEY DO NOT SUPPORT THE LEPTON's LABEL CLASSFICATION.

**Comment by leveled** [comment]
@Kyle-Ye could you point me in the direction of a good Gist Android client?

**Comment by Kyle-Ye** [comment]
Like the `bear` in the iOS/Mac, which supports ‘#’ as the label. As for the interface/UI, I recommend just like the Lepton in PC(Do not need to look like the one the git gist app usually did, because it is a app specially for Lepton Styled-gists not for the other git gists)
