### ISSUE TITLE
Error: socket hang up","cause":{"code":"ECONNRESET"}

### ISSUE THREAD

**Issue by pycrab** [hackjutsu/Lepton#365]
The more we know about your system and use case, the more easily and likely we can help.

#### Environment info
* OS: windows 10
* App Version (`Command/Ctrl + ,`): v1.8.0

#### Description of the problem / feature request / question:
本地修改完之前的gists之后点击提交或者Ctrl+S保存，然后刚写的就丢失了，还是原来的gists。
是因为网络比较差吗？

#### If possible, provide the log files
- Mac: `~/Library/Application Support/Lepton/logs`
- Windows: `C:\Users\<username>\AppData\Roaming\Lepton\logs`
- Linux: `~/.cached/Lepton/logs`
>The [debug mode](https://github.com/hackjutsu/Lepton/wiki) is recommended when producing the logs. 
>You can send your log file to cosmo.lepton@gmail.com if don't want to post it here.

**Comment by hackjutsu** [comment]
Very likely.

**Comment by superzhc** [comment]
你好，我遇到的现象是：
我对一个gist进行修改，之后点击submit，弹窗会关闭，等待一段时间，提示上传失败，我已经做的修改都会丢失

```json
{"name":"RequestError","message":"Error: socket hang up","cause":{"code":"ECONNRESET"},"error":{"code":"ECONNRESET"},"options":{"headers":{"User-Agent":"hackjutsu-lepton-app"},"method":"POST","uri":"https://api.github.com/gists","agent":{"_events":{},"_eventsCount":0,"_promisifiedCallback":true,"timeout":null,"proxy":{"protocol":"socks:","slashes":true,"auth":null,"host":"127.0.0.1:1080","port":"1080","hostname":"127.0.0.1","hash":null,"search":null,"query":null,"pathname":null,"path":null,"href":"socks://127.0.0.1:1080"},"proxyUri":"socks://127.0.0.1:1080"},"qs":{"access_token":"xxx"},"body":{"description":"xxx"}}},"json":true,"timeout":20000,"simple":true,"resolveWithFullResponse":false,"transform2xxOnly":false}}
```

根据上面的错误信息好像是网络问题，这种数据丢失了有什么好的方法来重新获取到？
非常感谢你开发这个软件，如果方便可以指导下，万分感谢！！！

**Comment by hackjutsu** [comment]
Depending on the suggestion here https://qr.ae/T9ReCj

**Comment by superzhc** [comment]
@hackjutsu 非常感谢你的回答，这种错误只是偶尔会出现，大部分时候都是可以提交成功的

**Comment by hackjutsu** [comment]
Close in favor of a similar issue. https://github.com/hackjutsu/Lepton/issues/354
