### ISSUE TITLE
Baidu Yunpan link need a password!

### ISSUE THREAD

**Issue by Carl-Wen** [hackjutsu/Lepton#366]
<img width="538" alt="屏幕快照 2019-07-28 下午10 33 58" src="https://user-images.githubusercontent.com/38063530/62008097-eb6cfb00-b187-11e9-8698-462cdae48e18.png">

**Comment by hackjutsu** [comment]
>Baidu Yunpan for China mainland users: (22dk)
https://pan.baidu.com/s/1Nszw5QH_U3FNK8bVQor3HQ#list/path=%2Flepton-1.8.0
https://github.com/hackjutsu/Lepton/releases/tag/v1.8.0

Doesn't `22dk` work?

**Comment by Carl-Wen** [comment]
It worked. Sorry about this, I did not think it is password for this.
