### ISSUE TITLE
Broken Syntax Highlighting for Markdown Code Block

### ISSUE THREAD

**Issue by anthonyattard** [hackjutsu/Lepton#368]
The code block is not properly highlighting. It works fine when in edit mode and on gist.github.com. See the screenshots.
![Screen Shot 2019-08-07 at 20 48 53](https://user-images.githubusercontent.com/8838135/62673909-02b0a300-b955-11e9-8230-fb5000ff7e9d.png)
![Screen Shot 2019-08-07 at 20 48 42](https://user-images.githubusercontent.com/8838135/62673910-02b0a300-b955-11e9-8f5d-79bf93ecf557.png)
![Screen Shot 2019-08-07 at 20 48 28](https://user-images.githubusercontent.com/8838135/62673912-03493980-b955-11e9-9381-0679b159430b.png)

**Comment by hackjutsu** [comment]
Thanks for reporting, do you have an example gist I can fork & test?

**Comment by anthonyattard** [comment]
I appreciate the quick response. Here is a link to the gist https://gist.github.com/anthonyattard/f6d36c8059b1bde909862a776d487a6c

**Comment by anthonyattard** [comment]
I have fixed the issue in the following pull request https://github.com/hackjutsu/Lepton/pull/369

**Comment by hackjutsu** [comment]
I’ll make a release this month! Thanks for the contribution!

**Comment by anthonyattard** [comment]
Sounds good!

**Comment by hackjutsu** [comment]
Sorry, the new release might be delayed to early September since I'm going for a vacation.

**Comment by hackjutsu** [comment]
@all-contributors please add @anthonyattard for code
