### ISSUE TITLE
Lepton from Server ?

### ISSUE THREAD

**Issue by SheepDomination** [hackjutsu/Lepton#375]
Can one run Lepton from a server and tie it together with any git ?

**Comment by anthonyattard** [comment]
What do you mean exactly? Not sure what you mean by "with any git".

**Comment by SheepDomination** [comment]
I want to run Lepton from my server, it seems it only can be installed locally; then tie that in with a self-hosted git ?

**Comment by hackjutsu** [comment]
Lepton doesn't have its own server. It uses the public GitHub gist service. If you want to host your own gist/snippet service, you might want to check out GitHub Enterprise or GitLab.

**Comment by SheepDomination** [comment]
@hackjutsu I'm running my own self-hosted git, but how do I install Lepton for any of the few self-hosting Gits available ?

**Comment by hackjutsu** [comment]
@SheepDomination Lepton is running on [GitHub v3 APIs](https://developer.github.com/v3/). If you have hosted GitHub Enterprise on your own server, you can connect Lepton to your hosted server by using token with gist enabled.

https://gist.github.com/hackjutsu/1ad7e4968eb64d881ec9dedd6c0f400b#file-leptonrc-L22-L27
