### ISSUE TITLE
Question: What does the public/private flag mean.  Visibility overall

### ISSUE THREAD

**Issue by hkokko** [hackjutsu/Lepton#379]
Who can see the snippets overall?

**Comment by josiahaltschuler** [comment]
I think this just designates whether or not the gist will be published on your GitHub account as "public" or "secret." Lepton uses the word "private" instead of "secret." If you publish a gist as private/secret, only you can can see it when you are logged in to your account. No one else.

**Comment by hackjutsu** [comment]
Thanks for the clarification. Yes, `private` means publishing the gists as `secret` in GitHub Gist. Maybe we should rename it as `secret` which is more accurate.

**Comment by hkokko** [comment]
Thanks. Would it be feasible to have the setting of the private be user defaultable. For example if one would like to have by default all of the gists secret - that would be a setting with the lepton. Currently one has to remember the clicking every time.


—h

**Comment by hackjutsu** [comment]
@hkokko , yes! Check out this section to explore different configuration options. Currently, we can set `newSnippetPrivate` as true to make `private/secret` as default selection.

https://github.com/hackjutsu/Lepton/blob/master/README.md#customization
