### ISSUE TITLE
Vscode extension

### ISSUE THREAD

**Issue by arangates** [hackjutsu/Lepton#384]
#### Description of the problem / feature request:
with the popularity of Vscode growing day by day , i think Vscode is the best place for such features.

![Screenshot from 2019-11-10 14-19-48](https://user-images.githubusercontent.com/7692801/68544607-41774e80-03c5-11ea-9faa-96689d51c20c.png)

**Comment by hackjutsu** [comment]
There is some cool VSCode gist extension like this https://marketplace.visualstudio.com/items?itemName=kenhowardpdx.vscode-gist
