### ISSUE TITLE
Tick private option by default and make the sidebar resizable 

### ISSUE THREAD

**Issue by ChristopherusColumbus** [hackjutsu/Lepton#386]
Environment info
* OS: MacOSX
* App Version: Lepton v1.8.1

#### Description of the problem / feature request / question:

1. Option to tick 'private' option by default. 
2. Make the sidebar and it's separate components resizable. I would like to be able to extend the height of the tags and reduce the height of the pinned items.

**Comment by hackjutsu** [comment]
> Option to tick 'private' option by default.

We create a `~/.leptonrc` with `snippet:newSnippetPrivate` enabled.

> Make the sidebar and it's separate components resizable. I would like to be able to extend the height of the tags and reduce the height of the pinned items.

The leftmost sidebar itself is not resizable. But we can "resize" the "LAUNGUAGES", "PINNED" and "TAGS" sections by clicking on the section titles.

**Comment by ChristopherusColumbus** [comment]
Thanks a lot!
