### ISSUE TITLE
Installing Lepton on Self-hosted Git ?

### ISSUE THREAD

**Issue by SheepDomination** [hackjutsu/Lepton#387]
Which command must I use to install Lepton as I'm using RedHat; and since I'm installing Lepton on a self-hosted git is there anything else I should know ?

**Comment by hackjutsu** [comment]
Hi @SheepDomination , thanks for your interst in Lepton! The app heavily relies on the [GitHub API v3](https://developer.github.com/v3/) for its Gist operations. If you are hosting a GitHub Enterprise, you can turn on the "enterprise:enable" flag in `.leptonrc` as described in https://gist.github.com/hackjutsu/1ad7e4968eb64d881ec9dedd6c0f400b.
