### ISSUE TITLE
Brew based macOS Binary not signed by Developer

### ISSUE THREAD

**Issue by ChristopherA** [hackjutsu/Lepton#392]
The more we know about your system and use case, the more easily and likely we can help.

#### Environment info
* OS: macOS 10.14.6
* App Version (`Command/Ctrl + ,`): 1.8.1

#### Description of the problem / feature request / question:

Installed via `brew cask install lepton`. Unable to run app on macOS because the file isn't signed by developer. 

-- Christopher Allen

**Comment by hackjutsu** [comment]
Thanks for reaching out! I think in this case, we need to explicitly give Lepton permission in Preference -> "Security & Privacy" because I no longer enrolled in Apple's developer program.
