### ISSUE TITLE
Support for Gitlab, and offline storage

### ISSUE THREAD

**Issue by ahmed-elsayed2017** [hackjutsu/Lepton#397]
I am just a new user to this application, and after using it for the first time. I found that it only supports GitHub. Is there any intentions to add support for Gitlab, or offline storage?

**Comment by hackjutsu** [comment]
Hi @ahmed-elsayed2017 , thanks for giving Lepton a try. Unfortunately, we don't have a plan to support GitLab or offline storage in the near future. But feel free to add this support if you want to play with the code! All contribution is welcome!
