### ISSUE TITLE
Missing scrollbar in edit

### ISSUE THREAD

**Issue by Nemecsek** [hackjutsu/Lepton#399]
#### Environment info
* OS: Windows 10 
* App Version: 1.8.2

#### Description of the problem / feature request / question:
The scrollbar in EDIT is completely missing. 
It is possible to scroll using the mouse wheel, but the standard scrollbar should show the relative position in the text.

**Comment by hackjutsu** [comment]
Thanks for the feedback. Yes, I think it's useful to show the scrollbar in the EDIT window.

**Comment by hackjutsu** [comment]
https://github.com/hackjutsu/Lepton/commit/1cb6651d4aec1234954235240f7acac2831c6147
