### ISSUE TITLE
Right scrollbar is too thin with multiple monitors

### ISSUE THREAD

**Issue by Nemecsek** [hackjutsu/Lepton#400]
#### Environment info
* OS: Windows 10 Pro
* App Version: 1.8.2

#### Description of the problem / feature request / question:
The scrollbar on the right is ok on a single monitor, but is an issue in case of multiple monitors: it is very difficult to pick it without moving the cursor to the monitor on the right. 

I would give the option to use standard (wide and uglier) toolbars or thinner (nicer) ones.

**Comment by hackjutsu** [comment]
Hi, could you provide some screenshots to illustrate these use cases? Thank you!

**Comment by hackjutsu** [comment]
1cb6651d4aec1234954235240f7acac2831c6147
