### ISSUE TITLE
Allow for storing snippets in Private GitHub Repository or possibly only on local machine?

### ISSUE THREAD

**Issue by macintacos** [hackjutsu/Lepton#403]
As far as I can tell, this app only allows you to store snippets that are in GitHub gists, which is a great premise. However, I deal with sensitive commands and data all the time, and putting them into gists just isn't feasible; even putting them into "private" gists isn't a good idea since private gists are just not-searchable gists. If someone has the link to them, they can still view the contents. That's unfortunately not enough security for me.

I'd really like it if this app could store code snippets locally, or perhaps in a private repository of your choice. I'm genuinely not sure how much of a rework that would need in order to be a reality, so I'm just asking here to see if there's something that I'm not thinking of when it comes to making this a reality.

If this isn't possible, I'm probably going to need to just use another app, but as of right now I'm keeping my options open.

**Comment by hackjutsu** [comment]
Hi, thanks for sharing your thoughts. Currently we don't have plans to add support for private repository or local machine. Even Lepton has these supported, I'm hesitant to suggest storing sensitive commands or data here since Lepton or gist is not designed for this type of information.

IMHO, I would try find some apps similar to 1Password which is specialized in the security field.

**Comment by macintacos** [comment]
I see where you're coming from, but I'm not even looking into something that heavy; it's like, I want to have code snippets available for things that would possibly reveal the inner workings of company software, so I'd like to keep that in a private repository instead of in a publicly viewable space (like gists). It's not like I'd be storing passwords or anything, but it's sensitive enough that I wouldn't want to put it in a gist that anyone can see if they have the right URL.

I'll probably end up using something like SnippetsLab, but I'd really love to have a solution that is built on top of git; I guess I'll just use VSCode+private git repository or something. Thanks!
