### ISSUE TITLE
Login-Slowly

### ISSUE THREAD

**Issue by jerry-IN** [hackjutsu/Lepton#405]
The more we know about your system and use case, the more easily and likely we can help.

#### Environment info
* OS: Windows 10
* App Version (`Command/Ctrl + ,`): 1.8.2

#### Description of the problem / feature request / question:
1、Why has Login for every?
2、Every Login needed 10 seconds(used proxy)。
3、Slowly、Slowly、Slowly。

#### If possible, provide the log files
- Mac: `~/Library/Application Support/Lepton/logs`
- Windows: `C:\Users\<username>\AppData\Roaming\Lepton\logs`
- Linux: `~/.cached/Lepton/logs`
>The [debug mode](https://github.com/hackjutsu/Lepton/wiki) is recommended when producing the logs. 
>You can send your log file to cosmo.lepton@gmail.com if don't want to post it here.

**Comment by hackjutsu** [comment]
This might be related to network conditions or issues on GitHub's service side which is out of Lepton's control.
