### ISSUE TITLE
Better Use Of Space (Left Nav: Languages, Pinned, Tags etc)

### ISSUE THREAD

**Issue by energylevels** [hackjutsu/Lepton#409]
The more we know about your system and use case, the more easily and likely we can help.

#### Environment info
*Windows 10 - 64 bit
* Lepton v1.9.0
*Display: 1920x1080 at 150%

#### Description of the problem / feature request / question:
On my 2 in 1 14-inch Lenovo Yoga Laptop the display is zoomed 150% for best display and Lepton's left nav/column is a bit frustrating - I think some of info there is already available in top menu anyway (new and sync) and the rest could be removed or relocated to free up some space. The languages section for example only shows three languages by defaul without having to scroll - It's minor, but thought I'd share FYI.

#### If possible, provide a sample gist or screenshot:
Screenshot: [https://www.webspectrum.co.uk/lepton.png](url)

#### If possible, provide the log files
- Mac: `~/Library/Application Support/Lepton/logs`
- Windows: `C:\Users\<username>\AppData\Roaming\Lepton\logs`
- Linux: `~/.cached/Lepton/logs`
>The [debug mode](https://github.com/hackjutsu/Lepton/wiki) is recommended when producing the logs. 
>You can send your log file to cosmo.lepton@gmail.com if don't want to post it here.

**Comment by hackjutsu** [comment]
Thanks for the feedback. Though not exactly match your need, the profile picture can be hidden by adding 
```
    "userPanel": {
        "hideProfilePhoto": true
    }
```
to `.leptonrc` configuration file.
https://gist.github.com/hackjutsu/1ad7e4968eb64d881ec9dedd6c0f400b

**Comment by hackjutsu** [comment]
If you are interested, feel free to play with the code and add options in `userPanel` to hide other section as well.

**Comment by energylevels** [comment]
Thanks, and I hadn't realised languages, pinned and tagged sections can be expanded/collapsed too - so that actually helps a lot on smaller screens.
