### ISSUE TITLE
代码高亮问题

### ISSUE THREAD

**Issue by xx-li** [hackjutsu/Lepton#41]
感谢作者的项目，挺好用的。 
发现对Objective-C没有高亮支持，另外Github Gist本身是支持Markdown的，但在Lepton中显示的是纯文本。

**Comment by hackjutsu** [comment]
Fixed: https://github.com/hackjutsu/Lepton/commit/0855abf9a90faef5e5605dfd0c60b8c2ec218c53

原来Highlight.js把Objective-C标记为`objectivec`，所以导致当我们输入Objective-C时候，它无法识别。

**Comment by hackjutsu** [comment]
忘了markdown这一点了。这个我研究一下，估计把markdown文件单独处理一下就行

**Comment by hackjutsu** [comment]
@xx-li Please have a test: Please have test: https://github.com/hackjutsu/Lepton/releases/tag/v1.0.0-beta.4
