### ISSUE TITLE
Write to Lepton with Python ?

### ISSUE THREAD

**Issue by SheepDomination** [hackjutsu/Lepton#410]
Can I write to Lepton language / pin  or tags with Python ?

**Comment by hackjutsu** [comment]
Could you elaborate your ask? I'm not sure if get it.

**Comment by SheepDomination** [comment]
Is there a python API to access Lepton though Python ?

**Comment by hackjutsu** [comment]
Lepton is backed by GitHub Gist which you can use Python to fetch data from. https://developer.github.com/v3/
