### ISSUE TITLE
Add more style to inline code in dark mode

### ISSUE THREAD

**Issue by amirmishani** [hackjutsu/Lepton#419]
I have a feature request for dark mode. In dark mode inline code blends too much into the regular text. I'm used to seeing a bit more styling on inline codes in light mode, however in dark mode only the font changes and there's a barely noticeable border around it and it's not enough to make the code pop out.

**Comment by hackjutsu** [comment]
Thanks for your feedback! Could you provide some screenshots so that we can better understand the issue?

**Comment by amirmishani** [comment]
The `this` keyword here is using inline code markdown but it's barely distinguishable. I realized that the same problem also exists on the light mode as well. I think they used to be a different color in earlier versions, I may be wrong on this. But I think they should be a different color so they can be easily noticeable. 

<img width="985" alt="Screen Shot 2020-05-06 at 11 11 28 AM" src="https://user-images.githubusercontent.com/11446580/81194662-eb0d5600-8f8a-11ea-9d8a-5126eeb77208.png">

<img width="703" alt="Screen Shot 2020-05-06 at 11 13 25 AM" src="https://user-images.githubusercontent.com/11446580/81195084-6111bd00-8f8b-11ea-9145-fdd94db714bd.png">

**Comment by hackjutsu** [comment]
![Uploading Screen Shot 2020-06-06 at 6.15.35 PM.png…]()
