### ISSUE TITLE
'Invalid filename' when I try to edit gist generate by vscode sync.

### ISSUE THREAD

**Issue by sunxyw** [hackjutsu/Lepton#420]
#### Environment info
* OS: Windows10 1909
* App Version (`Command/Ctrl + ,`): v1.9.0

#### Description of the problem / feature request / question:
I used settings sync extension in vscode and it creates a gist for sync settings. However, when I try to edit this gist in Lepton, it said that it's an invalid filename.
I know it's not a valid token for a filename in most OSs, this validation is useful for some careless users. But I think maybe you can let users selectively cancel this verification for some special needs.

#### If possible, provide a sample gist or screenshot:
* Sample gist: https://gist.github.com/sunxyw/48983e91bba1e3443439ef299fcf6454
* Screenshot: 
![image](https://user-images.githubusercontent.com/31698606/82008764-27823580-96a0-11ea-97f5-4fc061064fe2.png)

#### If possible, provide the log files
I can't find information about debug mode (in Wiki).
The log file will be sent to your email.

**Comment by hackjutsu** [comment]
Hi thanks for reaching out. As mentioned, Lepton validates the filenames by [valid-filename](https://github.com/sindresorhus/valid-filename).
https://github.com/hackjutsu/Lepton/blob/master/app/containers/gistEditorForm/index.js#L86-L89

But I do agree that we can make it more flexible for special use cases. If you are interested, you can try add the switch "validateFilename" in [.leptonrc](https://gist.github.com/hackjutsu/1ad7e4968eb64d881ec9dedd6c0f400b). You can learn more from this [PR](https://github.com/hackjutsu/Lepton/pull/404).

**Comment by hackjutsu** [comment]
https://github.com/hackjutsu/Lepton/pull/421
