### ISSUE TITLE
Cannot use behind a proxy

### ISSUE THREAD

**Issue by Xiao6** [hackjutsu/Lepton#45]
It will be good if proxy setting is supported.

**Comment by hackjutsu** [comment]
https://github.com/koichik/node-tunnel

**Comment by wujysh** [comment]
@hackjutsu 
I think protocol `socks5` is more commonly used in proxy, so I choose library `proxy-agent` instead.

**Comment by hackjutsu** [comment]
https://github.com/hackjutsu/Lepton/pull/87
