### ISSUE TITLE
1.9.1 release can't be open.

### ISSUE THREAD

**Issue by ksundong** [hackjutsu/Lepton#453]
The more we know about your system and use case, the more easily and likely we can help.

#### Environment info
* OS: macOS Catalina 10.15.5
* App Version (`Command/Ctrl + ,`): 1.9.1

#### Description of the problem / feature request / question:

application that inside the zip and dmg cannot be opened.

#### If possible, provide the log files
For Lepton after v1.9.0, the path of the log file can be found at `Command/Ctrl + ,`
- Mac: `~/Library/Application Support/Lepton/logs`
- Windows: `C:\Users\<username>\AppData\Roaming\Lepton\logs`
- Linux: `~/.cached/Lepton/logs`
>The [debug mode](https://github.com/hackjutsu/Lepton/wiki) is recommended when producing the logs. 
>You can send your log file to cosmo.lepton@gmail.com if don't want to post it here.

**Comment by hackjutsu** [comment]
https://github.com/hackjutsu/Lepton/issues/401

**Comment by mcfearsome** [comment]
Not sure if this the same as OP but I am having this issue that is not resolved with #401. For me the message displayed is `-1`

I am on Big Sur, searched for issues and didn't find any.
<img width="948" alt="Security___Privacy_and_costumesupercenter-production-app-app-release_yaml_—_costumesupercenter" src="https://user-images.githubusercontent.com/8698/91081876-cf02f280-e615-11ea-94d7-bdf8a4492f8c.png">

**Comment by PhilETaylor** [comment]
I just ran into this... I note though that I downloaded the ZIP Lepton-1.9.1-mac.zip and I was unable to get this to run, my Mac just told me that I did not have permission - and never prompted for allowing it:

<img width="336" alt="Screenshot 2020-09-26 at 20 33 31" src="https://user-images.githubusercontent.com/400092/94348861-8df86680-0037-11eb-836f-0fac0cbdac15.png">

However on installing from the DMG download `Lepton-1.9.1.dmg` I was correctly prompted (on right click and opening the app) to allow this app from an unidentified developer to run.

So if you have no luck with the zip file, try the DMG... worked for me.
