### ISSUE TITLE
lepton login failure

### ISSUE THREAD

**Issue by woshichuanqilz** [hackjutsu/Lepton#454]
The more we know about your system and use case, the more easily and likely we can help.

#### Environment info
* OS: win 10 
* App Version (`Command/Ctrl + ,`): 1.91

#### Description of the problem / feature request / question:
lepton login failure

After I enter my account and password show this loading page
![image](https://user-images.githubusercontent.com/11295355/84609941-71527b80-aeeb-11ea-8561-3523da7e8198.png)

3 ~ 4 secs later back to this page
![image](https://user-images.githubusercontent.com/11295355/84609931-6861aa00-aeeb-11ea-91e6-1143c8f80ab4.png)

Seems not my network issue cause I use [cacher](https://www.cacher.io/) login successfully. 
And my browswer can access gist. 

So why this issue came out? 

#### If possible, provide the log files
For Lepton after v1.9.0, the path of the log file can be found at `Command/Ctrl + ,`
- Mac: `~/Library/Application Support/Lepton/logs`
- Windows: `C:\Users\<username>\AppData\Roaming\Lepton\logs`
- Linux: `~/.cached/Lepton/logs`
>The [debug mode](https://github.com/hackjutsu/Lepton/wiki) is recommended when producing the logs. 
>You can send your log file to cosmo.lepton@gmail.com if don't want to post it here.

**Comment by hackjutsu** [comment]
> Seems not my network issue cause I use cacher login successfully.
Not sure what this means since they use different services.  Can you share more context like the log? Thanks.

**Comment by funway** [comment]
> 2020-07-19T11:31:42.173Z - error: The request has failed:
{"name":"RequestError","message":"Error: connect ECONNREFUSED 13.250.168.23:443","cause":{"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"13.250.168.23","port":443},"error":{"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"13.250.168.23","port":443},"options":{"uri":"https://api.github.com/user","agent":null,"headers":{"User-Agent":"hackjutsu-lepton-app","Authorization":"token 4c57************************"},"method":"GET","json":true,"timeout":20000,"simple":true,"resolveWithFullResponse":false,"transform2xxOnly":false}}
2020-07-19T11:31:42.174Z - info: [Dispatch] updateUserSession INACTIVE

It looks like the connection to Lepton's backend server (13.250.168.23) has been blocked by GFW. So I switched my system proxy to global mode, and it works! 😊

Hope Lepton could have a preference for proxy settings in the future. Thanks.

**Comment by leedorian** [comment]
> > 2020-07-19T11:31:42.173Z - error: The request has failed:
> > {"name":"RequestError","message":"Error: connect ECONNREFUSED 13.250.168.23:443","cause":{"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"13.250.168.23","port":443},"error":{"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"13.250.168.23","port":443},"options":{"uri":"[https://api.github.com/user","agent":null,"headers":{"User-Agent":"hackjutsu-lepton-app","Authorization":"token](https://api.github.com/user%22,%22agent%22:null,%22headers%22:%7B%22User-Agent%22:%22hackjutsu-lepton-app%22,%22Authorization%22:%22token) 4c57************************"},"method":"GET","json":true,"timeout":20000,"simple":true,"resolveWithFullResponse":false,"transform2xxOnly":false}}
> > 2020-07-19T11:31:42.174Z - info: [Dispatch] updateUserSession INACTIVE
> 
> It looks like the connection to Lepton's backend server (13.250.168.23) has been blocked by GFW. So I switched my system proxy to global mode, and it works! 😊
> 
> Hope Lepton could have a preference for proxy settings in the future. Thanks.

Yes, same issue here, F**K GFW, a proxy setting would be better.

**Comment by tsaeilae** [comment]
I have the same issue: 

debug: The gist number on this page is undefined
debug: The gist number on this page is undefined
error: The request has failed: TypeError: Cannot convert undefined or null to object
debug: -----> Failure with {}
error: The request has failed:
{}
info: [Dispatch] updateUserSession INACTIVE

**Comment by hackjutsu** [comment]
>Yes, same issue here, F**K GFW, a proxy setting would be better.

🤔

**Comment by MrCoder** [comment]
I have also come across this issue. I do not think it is a GFW issue. I am in Melbourne.
OS: Mac Big Sur (Mac Mini M1)
Node: 14
