### ISSUE TITLE
.leptonrc file not recognized

### ISSUE THREAD

**Issue by Grumium** [hackjutsu/Lepton#458]
#### Environment info
* OS: Linux Mint 20
* App Version: v1.9.1

#### Description of the problem:
```.leptonrc``` file is not recognized.
```chmod +rx``` was applied to the file

#### Log:

> ----- Lepton v1.9.1 linux-----

>info: [conf] Looking for .leptonrc at /home/user/snap/lepton/x1/.leptonrc
>info: [conf] The resolved configuration is ...
>info: "theme": "light"
>info: "autoUpdate": false
>info: "userPanel": {"hideProfilePhoto":false}
>info: "logger": {"level":"debug"}
>[...]

#### Content of /home/user/snap/lepton/x1/.leptonrc :
```
{
    "theme": "dark",
    "autoUpdate": true,
    "snippet": {
        "expanded": true,
        "newSnippetPrivate": false,
        "sorting": "updated_at",
        "sortingReverse": true
    },
    "editor" : {
        "tabSize": 4,
        "validateFilename": true
    },
    "userPanel": {
        "hideProfilePhoto": false
    },
    "logger": {
        "level": "debug"
    },
    "proxy": {
        "enable": false,
        "address": "socks://localhost:1080"
    },
    "notifications": {
        "success": true,
        "failure": true
    },
    "shortcuts": {
        "keyShortcutForSearch": "CMD+F",
        "keyNewGist": "CommandOrControl+N",
        "keyEditGist": "CommandOrControl+E",
        "keySubmitGist": "CommandOrControl+S",
        "keyImmersiveMode": "CommandOrControl+I",
        "keyAboutPage": "CommandOrControl+,",
        "keyDashboard": "CommandOrControl+D",
        "keyEditorExit": "CommandOrControl+Escape",
        "keySyncGists": "CommandOrControl+R"
    },
    "enterprise": {
        "enable": false,
        "host": "github_enterprise_host",
        "token": "token_with_gist_enabled",
        "avatarUrl": "optional_avatar_url"
    }
}
```

**Comment by itsgg** [comment]
Try starting lepton from terminal, it will display the expected .leptonrc file. If the file location is correct, check the syntax of the configration

```bash
anvil:  ~ 
→ lepton 
info: [conf] Looking for .leptonrc at /home/gg/snap/lepton/10/.leptonrc
info: 

```

**Comment by Grumium** [comment]
> Try starting lepton from terminal, it will display the expected .leptonrc file. If the file location is correct, check the syntax of the configration

Above is in fact the output I get after starting Lepton from terminal. There is no difference to the content of the log file. It just falls back to the default settings. You can check the Syntax of my .leptonrc file above. I cannot see any errors therein and I placed the file exactly where Lepton expects it to reside.
