### ISSUE TITLE
Mac Catalina 10.15.6 - Fails security, won't open

### ISSUE THREAD

**Issue by chrislachance** [hackjutsu/Lepton#460]
The more we know about your system and use case, the more easily and likely we can help.

#### Environment info
* OS: Mac Catalina 10.15.6
* App Version (`Command/Ctrl + ,`): Latest (as of this date)

#### Description of the problem / feature request / question:
Fails security verification, won't open.

#### If possible, provide a sample gist or screenshot:
<img width="476" alt="Screen Shot 2020-08-26 at 8 10 54 AM" src="https://user-images.githubusercontent.com/1014935/91301941-b3adf980-e773-11ea-9cfe-802465cdfdb1.png">

**Comment by meilinz** [comment]
Hi, please check out this post. https://github.com/hackjutsu/Lepton/issues/401
