### ISSUE TITLE
mac os, I can't find .leptonrc

### ISSUE THREAD

**Issue by Cynthia0329** [hackjutsu/Lepton#461]
#### Environment info
* OS: Mac OS v10.15.5
* App Version (`Command/Ctrl + ,`): Lepton v1.9.1

#### Description of the problem / feature request / question:
the path of the .leptonrc can be found at the About page by Command/Ctrl + ,

but I can't find .leptonrc in the path

I've set the show hidden file, but I still can't find it

why?

I just want to set a black theme, but now I can't T T

**Comment by hackjutsu** [comment]
Hi, you need you create the file by yourself. The path in the about page is just a convenient indicator of where the file should be created.
https://github.com/hackjutsu/Lepton#customization
