### ISSUE TITLE
Name invalid when update vs code setting sync file

### ISSUE THREAD

**Issue by PhantasWeng** [hackjutsu/Lepton#462]
The more we know about your system and use case, the more easily and likely we can help.

#### Environment info
* OS: mac 10.15.7
* App Version (`Command/Ctrl + ,`): v1.9.1

#### Description of the problem / feature request / question:
The Vs Code Setting Sync plugin will create file name with "|", which make update failed because of name invalid.
Gist accepts this kind of filename format.

#### If possible, provide a sample gist or screenshot:
![image](https://user-images.githubusercontent.com/5707062/95741651-3279da00-0cc1-11eb-92cc-35686bfa85a8.png)

#### If possible, provide the log files
For Lepton after v1.9.0, the path of the log file can be found at `Command/Ctrl + ,`
- Mac: `~/Library/Application Support/Lepton/logs`
- Windows: `C:\Users\<username>\AppData\Roaming\Lepton\logs`
- Linux: `~/.cached/Lepton/logs`
>The [debug mode](https://github.com/hackjutsu/Lepton/wiki) is recommended when producing the logs. 
>You can send your log file to cosmo.lepton@gmail.com if don't want to post it here.

**Comment by hackjutsu** [comment]
There could be two options:
1. [turn off the filename validation in .leptonrc](https://github.com/hackjutsu/Lepton/wiki/Configuration)
2. report a bug in VS Code if you like :)
