### ISSUE TITLE
搜索框无法关闭【请给搜索框增加一个关闭按钮】

### ISSUE THREAD

**Issue by stfenjobs** [hackjutsu/Lepton#469]
The more we know about your system and use case, the more easily and likely we can help.

#### Environment info
* OS:  mac
* App Version (`Command/Ctrl + ,`): 版本1.9.1 (1.9.1)

#### Description of the problem / feature request / question:
搜索框无法关闭【请给搜索框增加一个关闭按钮】

我打算搜索，但是又不想搜索了，无法关闭这个 搜索框， 按ESC也不行
![image](https://user-images.githubusercontent.com/6580897/100548377-26fd6500-32a7-11eb-8fba-77efff94efbe.png)

#### If possible, provide the log files
For Lepton after v1.9.0, the path of the log file can be found at `Command/Ctrl + ,`
- Mac: `~/Library/Application Support/Lepton/logs`
- Windows: `C:\Users\<username>\AppData\Roaming\Lepton\logs`
- Linux: `~/.cached/Lepton/logs`
>The [debug mode](https://github.com/hackjutsu/Lepton/wiki) is recommended when producing the logs. 
>You can send your log file to cosmo.lepton@gmail.com if don't want to post it here.

**Comment by PMExtra** [comment]
Please focus the input, then press ESC.
请先把焦点定位到输入框中，再按下ESC键。

**Comment by hackjutsu** [comment]
The search bar can be toggled by "shift + space".
