### ISSUE TITLE
当我输入一个错误的标签，也会搜索出来

### ISSUE THREAD

**Issue by stfenjobs** [hackjutsu/Lepton#470]
The more we know about your system and use case, the more easily and likely we can help.

#### Environment info
* OS: mac os
* App Version (`Command/Ctrl + ,`):版本1.9.1 (1.9.1)

#### Description of the problem / feature request / question:
这个标签 test33是不存在的，但还是搜出了东西

![image](https://user-images.githubusercontent.com/6580897/100548418-63c95c00-32a7-11eb-841b-93e07c2c939a.png)

#### If possible, provide the log files
For Lepton after v1.9.0, the path of the log file can be found at `Command/Ctrl + ,`
- Mac: `~/Library/Application Support/Lepton/logs`
- Windows: `C:\Users\<username>\AppData\Roaming\Lepton\logs`
- Linux: `~/.cached/Lepton/logs`
>The [debug mode](https://github.com/hackjutsu/Lepton/wiki) is recommended when producing the logs. 
>You can send your log file to cosmo.lepton@gmail.com if don't want to post it here.

**Comment by hackjutsu** [comment]
Lepton uses the fuzzy search backed by fuse.js. Therefore it can return the results which the engine thinks are close enough (with high relevance scores).
