### ISSUE TITLE
.leptonrc not loading

### ISSUE THREAD

**Issue by seebeen** [hackjutsu/Lepton#472]
The more we know about your system and use case, the more easily and likely we can help.

#### Environment info
* OS: Windows 10 20H2
* App Version (`Command/Ctrl + ,`): Lepton v1.9.1

#### Description of the problem / feature request / question:

.leptonrc not loaded.

Lepton confguration file is saved in proper location, but it doesn't load. 

Configuration file contents are:

```
{
    "theme": "dark",
    "autoupdate: true,
    "userPanel": {
        "hideProfilePhoto": true
    },
}
```

#### If possible, provide the log files
For Lepton after v1.9.0, the path of the log file can be found at `Command/Ctrl + ,`
- Mac: `~/Library/Application Support/Lepton/logs`
- Windows: `C:\Users\<username>\AppData\Roaming\Lepton\logs`
- Linux: `~/.cached/Lepton/logs`
>The [debug mode](https://github.com/hackjutsu/Lepton/wiki) is recommended when producing the logs. 
>You can send your log file to cosmo.lepton@gmail.com if don't want to post it here.

2020-12-08T11:36:32.372Z - info: 

----- Lepton v1.9.1 win32-----

2020-12-08T11:36:32.372Z - info: [conf] Looking for .leptonrc at C:\Users\Sibin Grasic/.leptonrc
2020-12-08T11:36:32.372Z - info: [conf] The resolved configuration is ...
2020-12-08T11:36:32.372Z - info: "theme": "light"
2020-12-08T11:36:32.372Z - info: "autoUpdate": false
2020-12-08T11:36:32.373Z - info: "userPanel": {"hideProfilePhoto":false}
2020-12-08T11:36:32.373Z - info: "logger": {"level":"debug"}
2020-12-08T11:36:32.373Z - info: "proxy": {"enable":false,"address":"socks://localhost:1080"}
2020-12-08T11:36:32.373Z - info: "snippet":

**Comment by nkzhengwt** [comment]
the same.
There is not .leptonrc in the folder after ctrl+comma.
Platform: Windows 10

**Comment by alpipego** [comment]
Your snippet is not valid JSON, this will work:

```
{
    "theme": "dark",
    "autoupdate": true,
    "userPanel": {
        "hideProfilePhoto": true
    }
}
```

**Comment by seebeen** [comment]
Well, I feel like an idiot. 😢

**Comment by kauanmocelin** [comment]
I maked exactly same error. It's the habit for prevent errors on js objects with this comma :smile:

**Comment by kinduff** [comment]
Happen to me too, until I stumbled in this thread. I have my opinions about JSON as config, TOML is pretty nice for these kind of things.
