### ISSUE TITLE
A suggestion on GUI to help better tags management

### ISSUE THREAD

**Issue by qshfan** [hackjutsu/Lepton#473]
The more we know about your system and use case, the more easily and likely we can help.

#### Environment info
* OS: MacOS 10.15
* App Version (`Command/Ctrl + ,`): 1.9.1

#### Description of the problem / feature request / question:
I use Lepton mainly to manage my gists on github, where I consider tags as a powerful tool when it comes to a management of gists, especially the amount of files and connections increase. 
Lepton supports now to show the gists per tags, but the area where I can see my tags are really small. It would be nice if the user can choose to make it bigger and have a better view of tags. 

#### If possible, provide a sample gist or screenshot:
<img width="319" alt="image" src="https://user-images.githubusercontent.com/74938360/103553694-1cd61400-4eae-11eb-81cb-52898c74a994.png">

#### If possible, provide the log files
For Lepton after v1.9.0, the path of the log file can be found at `Command/Ctrl + ,`
- Mac: `~/Library/Application Support/Lepton/logs`
- Windows: `C:\Users\<username>\AppData\Roaming\Lepton\logs`
- Linux: `~/.cached/Lepton/logs`
>The [debug mode](https://github.com/hackjutsu/Lepton/wiki) is recommended when producing the logs. 
>You can send your log file to cosmo.lepton@gmail.com if don't want to post it here.

**Comment by hackjutsu** [comment]
The sections can expand if you double click on the "TAGS" or "PINNED".

**Comment by qshfan** [comment]
> The sections can expand if you double click on the section titles like "TAGS" or "PINNED".

cool, it worked. Thanks for the hint!
