### ISSUE TITLE
Install Documentation Update: '--cask' not 'cask'

### ISSUE THREAD

**Issue by threeoceansassets** [hackjutsu/Lepton#479]
The more we know about your system and use case, the more easily and likely we can help.

#### Environment info
* OS: Mac OS XI
* App Version: N/A

#### Description of the problem / feature request / question:
GitHub install instructions read: 

> Install via Homebrew (macOS)

`brew cask install lepton`

As of brew 2.7.0, per [this brew issue](https://github.com/Homebrew/discussions/discussions/340)  

> `brew cask <command>` was deprecated in favor of `brew <command> --cask`

Install documentation should reflect this change.

**Log**

==> Tapping homebrew/cask
Cloning into '/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask'...
remote: Enumerating objects: 35, done.
remote: Counting objects: 100% (35/35), done.
remote: Compressing objects: 100% (25/25), done.
remote: Total 548126 (delta 16), reused 21 (delta 10), pack-reused 548091
Receiving objects: 100% (548126/548126), 241.73 MiB | 1.46 MiB/s, done.
Resolving deltas: 100% (387090/387090), done.
Tapped 3806 casks (3,927 files, 259.3MB).
Error: Calling `brew cask install` is disabled! Use brew install [--cask] instead.

**Comment by JohannesFischer** [comment]
Looks like this has already been updated: https://github.com/hackjutsu/Lepton#installation
