### ISSUE TITLE
Can no longer login due to deprecating through query param

### ISSUE THREAD

**Issue by sunnysidesounds** [hackjutsu/Lepton#489]
The more we know about your system and use case, the more easily and likely we can help.

#### Environment info
* OS: macOS Catalina 10.15.7
* App Version: 1.9.1

#### Description of the problem / feature request / question:
I can no longer log in to Github gist with Lepton. 

#### If possible, provide a sample gist or screenshot:
Looks like Gihub no longer accepts query parameter authentication. Only header-based. From the log: 

- ERROR message: `Must specify access token via Authorization header.`
- ERROR message line [https://developer.github.com/changes/2020-02-10-deprecating-auth-through-query-param/](https://developer.github.com/changes/2020-02-10-deprecating-auth-through-query-param/) Looks like May 5 is the first brownout scheduled. (See link)

<img width="1008" alt="Screen Shot 2021-05-05 at 10 31 09 AM" src="https://user-images.githubusercontent.com/1030838/117183957-08872280-ad8d-11eb-8913-db84ce67c15c.png">

#### If possible, provide the log files
[2021-05-05T17.14.14.608Z.log](https://github.com/hackjutsu/Lepton/files/6429088/2021-05-05T17.14.14.608Z.log)

**Comment by jasonminsookim** [comment]
I'm having the same issue and am not able to login.

**Comment by EdwardCuiPeacock** [comment]
I am having the same issue.

**Comment by sunnysidesounds** [comment]
I was able to fix it by modifying this file and rebuilding it: https://github.com/sunnysidesounds/Lepton/blob/master/app/utilities/githubApi/index.js

I ended up having to set up a development environment to fix the issue. When I have time I can or someone else can submit a PR to add this change in.

**Comment by EdZava** [comment]
@sunnysidesounds 
Could you pass what was the change you made in the file?

**Comment by EdZava** [comment]
Thank you so much @sunnysidesounds! 👏
I have created the pull request from your changes.

**Comment by EdZava** [comment]
Does anyone know if this project is dead?
Or is there a fork that does have support?

**Comment by sunnysidesounds** [comment]
I have a fork I created with the fixes as well as several other changes I made. You are more than welcome to pull it down and build it and use it. But as a note, this is use at your own risk and I won't support any changes or fix any issues. I made the changes for my own personal use. 

Forked Repo https://github.com/sunnysidesounds/Lepton
