### ISSUE TITLE
About Color theme setting in the portable version

### ISSUE THREAD

**Issue by AntaresShao** [hackjutsu/Lepton#492]
The more we know about your system and use case, the more easily and likely we can help.

#### Environment info
* OS: Windows 10
* App Version (`Command/Ctrl + ,`): 1.9.1-Portable

#### Description of the problem / feature request / question:
Sorry, I have some silly questions here.
There is no `.leptonrc` file in my home directory. How do I change the appearance of the whole interface into dark mode? I tried to use the __Developer tools__ to change the color and I met these two questions:
  1. After I changed the color and close the application, the interface returned to the light mode when I reopened it.
  2. When I finished the dark background and grey text color changing, the syntax highlight was till fitting the light mode, I couldn't see the code clearly. I'm wondering how I can change the syntax highlight color theme.

#### If possible, provide the log files

[2021-05-19T08.26.14.181Z.log](https://github.com/hackjutsu/Lepton/files/6507541/2021-05-19T08.26.14.181Z.log)
[2021-05-19T09.10.59.530Z.log](https://github.com/hackjutsu/Lepton/files/6507542/2021-05-19T09.10.59.530Z.log)

For Lepton after v1.9.0, the path of the log file can be found at `Command/Ctrl + ,`
- Mac: `~/Library/Application Support/Lepton/logs`
- Windows: `C:\Users\<username>\AppData\Roaming\Lepton\logs`
- Linux: `~/.cached/Lepton/logs`

>The [debug mode](https://github.com/hackjutsu/Lepton/wiki) is recommended when producing the logs. 
>You can send your log file to cosmo.lepton@gmail.com if don't want to post it here.

**Comment by hackjutsu** [comment]
Oh, you have to create the file yourself if you want to further configure the app.
