### ISSUE TITLE
功能请求

### ISSUE THREAD

**Issue by wqcblog** [hackjutsu/Lepton#519]
Hello, lepton is a great application. I'm looking forward to whether it will support iPad. Thank you

**Comment by andy1li** [comment]
Unfortunately, its' Apple who doesn't support Electron to run on iPad. 😥

**Comment by wqcblog** [comment]
Thank you for your reply. Lepton is a great software. Thank you for creating it. I would like to ask if lepton has the option of folding all (I know that it can be folded one by one manually). When gist has more content, it is very troublesome to scroll to find it. Can you support it? Thank you! I wish you a happy life and work!





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hackjutsu/Lepton"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月19日(星期天) 中午12:38
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [hackjutsu/Lepton] 功能请求 (#519)





 
Unfortunately, its' Apple who doesn't support Electron to run on iPad. 😥
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by andy1li** [comment]
I'm not the author or a contributor. 😅 (I had trouble logging in the other day, so was browsing the issues to see whether someone else had the same problem. (Well, updating to the latest version solved my problem.) )

**Comment by hackjutsu** [comment]
Thanks for the discussion. As Andy mentioned, iPad doesn't support Electron and it's non-trivial to port the app to native iOS bundle.
