### ISSUE TITLE
jupyter notebook

### ISSUE THREAD

**Issue by wangxiatian** [hackjutsu/Lepton#525]
The more we know about your system and use case, the more easily and likely we can help.

#### Environment info
* OS: win10
* App Version (`Command/Ctrl + ,`):v1.10.0

#### Description of the problem / feature request / question:
I have made a `ipynb` file, and sort to `#jupyter lab`. But compared to the  picture of Lepton
it seems don't have the run answer. How can I get the cell run answer ?
#### If possible, provide a sample gist or screenshot:
![image](https://user-images.githubusercontent.com/41409166/151295197-e27715eb-622d-4b0b-9628-c1ed47f384e9.png)
![official ans](https://github.com/hackjutsu/Lepton/blob/master/docs/img/portfolio/jupyterNotebook.png
)

**Comment by hackjutsu** [comment]
🤔 Lepton can only render the 'ipynb' files, not run the code inside them.
