### ISSUE TITLE
“Lepton.app” cannot be opened because the developer cannot be verified.

### ISSUE THREAD

**Issue by xareelee** [hackjutsu/Lepton#526]
#### Environment info
* OS: macOS 11.6.3
* App Version (`Command/Ctrl + ,`): 1.10.0

#### Description of the problem / feature request / question:

After installing Lepton by homebrew on my Mac:

```
brew install lepton --cask
```

It shows an alert when I open this app:

> “Lepton.app” cannot be opened because the developer cannot be verified.
> 
> macOS cannot verify that this app is free from malware.
> Homebrew Cask downloaded this file today at 09:47 from hackjutsu.com.

Is that possible to add a verified provisioning profile to this Mac App?

Other electron apps did not encounter this problem.

**Comment by hackjutsu** [comment]
https://github.com/hackjutsu/Lepton/issues/401

Thanks for reporting, pls check out this post.
