### ISSUE TITLE
Use tab in the edit/new dialog

### ISSUE THREAD

**Issue by hackjutsu** [hackjutsu/Lepton#53]
My implementation for enabling tabs has flaws, so I disabled that. I would like to ask for some front-end engineer for help.

**Comment by Owlree** [comment]
Do you want to disable tab navigation / focusing altogether or just make it unavailable when editing a gist?

**Comment by hackjutsu** [comment]
@Owlree Only for editing the gist now. 

Might enable that when I find a good solution. (I'm not a front-end developer so I need some time for researching.)

**Comment by Owlree** [comment]
I think I can help, but I am not sure what is the intended behavior. I just took a look at Atom and tab focusing is enabled, but it skips text inputs altogether.

e.g.
Pressing tab on
- Button 1 <- Focused
- Text input
- Button 2

skips to
- Button 1
- Text input
- Button 2 <- Focused

**Comment by wujysh** [comment]
I think the tab button should function like following: 
If it is pressed when
* text input is focused
  * a tab character or spaces should be inserted in the input
* otherwise
  * switch the focus to the next element of the window

It's convenient to insert tabs or spaces to align code blocks.

**Comment by hackjutsu** [comment]
Hey guys,

Checkout this code and play your tricks on it. The editor is a `textarea` wrapped inside a redux-form.
https://github.com/hackjutsu/Lepton/blob/master/app/containers/gistEditorForm/index.js
```javascript
const renderContentField = ({ input, type, placeholder, meta: { touched, error, warning } }) => (
  <div>
    <textarea className='gist-editor-content-area' { ...input } type={ type } placeholder={ placeholder }/>
    { touched && ((error && <span className='error-msg'>{error}</span>) ||
      (warning && <span className='error-msg'>{warning}</span>)) }
  </div>
)
```

I would like to focus on improving the search quality these days, and need some experts' help on this tab issue.

**Comment by hackjutsu** [comment]
I agree with @wujysh .

**Comment by wujysh** [comment]
@hackjutsu
Is it a option to embed other powerful code editor in the content area? e.g. [CodeMirror](https://codemirror.net/)
That will solve the tab issue indirectly and enhance editing experience.

**Comment by Owlree** [comment]
@wujysh The problem with your approach is that you are pressing tab to cycle through the elements in the page and once you focus the `textarea` you stop cycling and instead you start inserting tabs.

**Comment by wujysh** [comment]
@Owlree Is it conflict?
I think cycle through the elements can be even sacrificed to ensure inserting tab character or spaces in the `textarea` is working.

**Comment by wujysh** [comment]
@hackjutsu @Owlree 
I think this is a basic plan good for now, or we should embed other editors.
http://stackoverflow.com/a/37697925/5209833

**Comment by hackjutsu** [comment]
@Owlree @wujysh We can observe how GitHub Gist's own online gist editor behaves. Once the text area gets focused, it begins to insert tabs.

**Comment by hackjutsu** [comment]
@wujysh I'm open to 3rd party editor.

**Comment by hackjutsu** [comment]
@wujysh @Owlree @dukewan 

Thank you guys! This issue has been solved by introducing the 3rd-party editor [CodeMirror](https://codemirror.net/). A huge thanks for @wujysh 's PR!

New editor will be available in the next release this week.
