### ISSUE TITLE
Support for Github Enterprise

### ISSUE THREAD

**Issue by tmr232** [hackjutsu/Lepton#54]

**Comment by hackjutsu** [comment]
I don't have a GitHub Enterprise account for development or testing. 

PR will be welcome on this topic.

**Comment by tmr232** [comment]
Seems like replacing the relevant URLs in the code solves *nearly* everything.
The only issue remaining is that the avatar does not show. The URL is right, but it does not work.
I am sorry to be unable to provide more info. But do you have any ideas what might cause the issue?

**Comment by hackjutsu** [comment]
The image url comes from the `avatar_url` field of the profile object. 
https://github.com/hackjutsu/Lepton/blob/master/app/containers/userPanel/index.js
```javascript
  renderProfile () {
    let profile = this.props.userSession.profile
    if (!profile || this.props.userSession.activeStatus === 'INACTIVE') {
      return
    }

    return (
      <div>
        <Image className='profile-image-section' src={ profile.avatar_url } onClick={ this.handleProfileImageClicked.bind(this) } rounded/>
      </div>
    )
  }
```
The profile object comes from the `initUserSession` method from `/app/index.js`, which then calls `getUserProfile()` from `/app/utilities/githubApi`.

**Comment by johnwebbcole** [comment]
@tmr232 were you able to get it working with gh enterprise?

**Comment by hackjutsu** [comment]
@johnwebbcole 

I don't have an Enterprise account, so any help or PR would be appreciated.

**Comment by tmr232** [comment]
@johnwebbcole Yes, it was done by replacing all the API URIs in the code.
To make something that supports both public & enterprise Github we need to add a configuration file or something similar.

**Comment by hackjutsu** [comment]
https://github.com/hackjutsu/Lepton/commit/b2bebeda111d1911088007b77f97c732e0fe48ac
