### ISSUE TITLE
Immersive Full-App Mode for gist content

### ISSUE THREAD

**Issue by hackjutsu** [hackjutsu/Lepton#56]
It would be nice to have an immersive mode for the gist content.

**Comment by hackjutsu** [comment]
done:https://github.com/hackjutsu/Lepton/commit/a27f1ca72a8698d9599922448aa94b79b6d36dda

**Comment by hackjutsu** [comment]
![image](https://cloud.githubusercontent.com/assets/7756581/22638151/2747f378-ebfb-11e6-86a0-bb0c4a1794ee.png)

![image](https://cloud.githubusercontent.com/assets/7756581/22638154/32a66fec-ebfb-11e6-9662-d9056e9f62fd.png)

**Comment by hackjutsu** [comment]
@wujysh 

We only have access to the small highlighted area. The large `panel-heading` class, which comes with the Bootstrap React Panel component, is not exposed to add a double click listener.

IMHO, adding double click to such a small area doesn't seem to be a good idea.

![image](https://cloud.githubusercontent.com/assets/7756581/22679380/8d8e78e4-ecb6-11e6-8181-541f770866d8.png)

**Comment by wujysh** [comment]
https://github.com/hackjutsu/Lepton/blob/master/app/containers/snippet/index.js#L442
@hackjutsu  Can double click listener be placed here?

**Comment by hackjutsu** [comment]
<img width="1096" alt="screen shot 2017-02-06 at 10 32 49 pm" src="https://cloud.githubusercontent.com/assets/7756581/22680354/4c6d7292-ecbc-11e6-83cc-4c89eb6d275d.png">

Might not be a good idea either.

**Comment by wujysh** [comment]
@hackjutsu I am not familiar with react-bootstrap.
There is even no double click API exposed on `Panel`.
Perhaps, it's complex to implement that. Split the `Panel` into `<div class='panel-header' ...>` manually etc.

**Comment by hackjutsu** [comment]
@wujysh 

I refrain from applying too many hacky tricks here, because it will make the code out of our control quickly. Maybe `command + i` is good enough :)

**Comment by wujysh** [comment]
@hackjutsu OK, I agree.

**Comment by hackjutsu** [comment]
@wujysh Thank you for your research:)
