### ISSUE TITLE
i can't login in github.com

### ISSUE THREAD

**Issue by uuair** [hackjutsu/Lepton#58]
![](http://i.imgur.com/AXvqI9M.png)

log:
```
2017-02-06T01:46:38.833Z - info: Found user profile null
2017-02-06T01:46:38.989Z - info: Checking for update
2017-02-06T01:46:44.206Z - info: [Dispatch] updateAuthWindowStatus ON
2017-02-06T01:47:15.347Z - info: Update for version 1.0.0 is not available (latest version: 1.0.0)
2017-02-06T01:47:15.347Z - debug: [autoUpdater] update-not-available
```

![](http://i.imgur.com/ApZuk3U.png)

**Comment by hackjutsu** [comment]
@uuair Can you show me the error log inside the Console tab?

![image](https://cloud.githubusercontent.com/assets/7756581/22634656/da6c2b92-ebe0-11e6-9e5d-914aeae31703.png)

**Comment by uuair** [comment]
<img width="1380" alt="2017-02-09 10 04 45" src="https://cloud.githubusercontent.com/assets/2612307/22766224/465093ea-eeaf-11e6-8884-7077177e4b9a.png">

**Comment by hackjutsu** [comment]
@uuair Sorry, I have no idea about that. Maybe it was somehow blocked. 

Did you try to run behind a proxy?

**Comment by uuair** [comment]
github.com site is in my proxy server access list....Surge access list.

**Comment by hackjutsu** [comment]
@uuair Does it happen when you click on the login button, even before entering any credentials?

**Comment by hackjutsu** [comment]
Not enough information. Will reopen it when necessary.
