### ISSUE TITLE
`npm run pack` script is removed, readme should be updated

### ISSUE THREAD

**Issue by wujysh** [hackjutsu/Lepton#59]
In the commit 4ba4c16ccae96182a5e89e7254b7aa987962aa01, `npm run pack` script is removed from `package.json`.
It's conflict with the instructions in `README.md`.
Update is needed.

**Comment by hackjutsu** [comment]
Thank you. I'll add it back soon.

**Comment by wujysh** [comment]
Solve in #61, thanks.
