### ISSUE TITLE
Resizable panels

### ISSUE THREAD

**Issue by hackjutsu** [hackjutsu/Lepton#70]
![image](https://cloud.githubusercontent.com/assets/7756581/22678397/98bc6800-ecae-11e6-961f-0d51810a8e3d.png)

**Comment by hackjutsu** [comment]
![gmnfczbios](https://cloud.githubusercontent.com/assets/7756581/22678545/bb4c864c-ecaf-11e6-8496-5600f9997af0.gif)

**Comment by wujysh** [comment]
It's awesome. 
#56
Maybe you could let double clicking the gist panel title to enter the immersive mode. Or something else?
Remembering shortcuts is boring.

**Comment by hackjutsu** [comment]
@wujysh Sounds like a good idea:)

**Comment by hackjutsu** [comment]
@wujysh Want a beta version for [milestone v1.1.0]( https://github.com/hackjutsu/Lepton/milestone/10)?
https://share.weiyun.com/331736ff209eac8390c189f6ec67c8e5

**Comment by wujysh** [comment]
@hackjutsu Could you give me Linux version?

**Comment by wujysh** [comment]
@hackjutsu You can checkout a dev branch, and I can take responsible for testing on Linux.

**Comment by hackjutsu** [comment]
@wujysh feel free to check the dev branch.
