### ISSUE TITLE
Can we collapse the gist?

### ISSUE THREAD

**Issue by hackjutsu** [hackjutsu/Lepton#74]
![image](https://cloud.githubusercontent.com/assets/7756581/22720673/fd0cf2ae-ed60-11e6-9771-4cccacf9bd06.png)

**Comment by wujysh** [comment]
I think it might be an option for user to choose.

**Comment by hackjutsu** [comment]
@wujysh Yes, by default expanded, but can be collapsed.

**Comment by hackjutsu** [comment]
affc30e0418b7b1060f60631888a1a2800ab73b5
4e5eead4a8d6a79fa9a1766c23ec5155fe981adf
affc30e0418b7b1060f60631888a1a2800ab73b5
