### ISSUE TITLE
Don't open search while edit/new modal open?

### ISSUE THREAD

**Issue by CodeBrauer** [hackjutsu/Lepton#79]
When you accidentally press <kbd>Shift</kbd>+<kbd>Space</kbd> in modals while in a new/edit modal it opens the search box and loses focus in the current input.

![demogif](https://cl.ly/0V1n0N3l3m0w/Screen%20Recording%202017-02-08%20at%2012.49%20nachm..gif)

**Comment by hackjutsu** [comment]
Thanks, it has been addressed. The next release will contain the fix.
