### ISSUE TITLE
 CodeMirror Editor Enhancement

### ISSUE THREAD

**Issue by hackjutsu** [hackjutsu/Lepton#84]
Should we enable addons for CodeMirror? Which addons to enable?

**Comment by wujysh** [comment]
Pending features:
- [ ] language highlighting according to filename
- [ ] tab character / indent unit setting
- [ ] editor theme setting
- [ ] turn on CodeMirror addons
- [ ] keybinding on editor

**Comment by wujysh** [comment]
@hackjutsu 
* Language highlighting according to filename:
Now, I'm not sure how to implement the interaction between filename input field and content textarea field powered by CodeMirror. 
I think the class `GistEditorForm` need to be refactored like extracting the relavant fields and textarea into a new class. I guess:) You can have a try.
* Indent character/unit setting:
I think we can mock GitHub Gist website for selecting tab/space and unit. It's also powered by CodeMirror.
* Editor theme setting:
There is no gist-like style in native CodeMirror package. We can override css like https://gist.github.com/k2052/6847000.
* Keymaps on editor: Which native-supported one to choose?
  * emacs
  * sublime
  * vim
* Enable CodeMirror addons: https://codemirror.net/doc/manual.html#addons

**Comment by hackjutsu** [comment]
Thank you for the effort:)

>Language highlighting according to filename

The form is implemented by `redux-form` which means you can get the filename value from redux state `gistFiles`.

>Indent character/unit setting

We can do this at the GitHub API level.

>Editor theme setting

Nice to have ;)

>Keymaps on editor: Which native-supported one to choose?

I don't think this is necessary.
