### ISSUE TITLE
About Page

### ISSUE THREAD

**Issue by hackjutsu** [hackjutsu/Lepton#85]
The Windows version doesn't come with an About page like the mac verion.

It would be nice if there is an About page to show:
- Application versioin
- GitHub link
- License
- Thanks to contributors

**Comment by hackjutsu** [comment]
![image](https://cloud.githubusercontent.com/assets/7756581/23276632/ed908a78-f9bf-11e6-8b12-7d2fca70ca2f.png)

**Comment by ApolloZhu** [comment]
Could you please add a close button? Took me a while to figure out how to close this window (by accidentally pressing the escape key).

**Comment by hackjutsu** [comment]
@ApolloZhu 

Thanks! This is a good feedback!

**Comment by hackjutsu** [comment]
@ApolloZhu Fixed in v1.4.5 release.
