### ISSUE TITLE
CodeMirror gutter should fill up the editor

### ISSUE THREAD

**Issue by wujysh** [hackjutsu/Lepton#88]
![image](https://cloud.githubusercontent.com/assets/5550402/22781305/e27753ce-eefc-11e6-96b1-e717d3b23f08.png)

The `min-height` setting of CodeMirror editor cause the line number column becomes too short.

**Comment by hackjutsu** [comment]
@wujysh Just curious, are you testing on macOS or Linux?

**Comment by wujysh** [comment]
@hackjutsu
Linux. There is no problem on macOS?

2017年2月10日 上午4:41，"Cosmo" <notifications@github.com>写道：

**Comment by hackjutsu** [comment]
@wujysh 

No, not about this issue. As I know, the Electron's notifications might not work on some Linux platforms,  so I'm curious whether you have received notifications when performing the `sync` `create`, `edit`, `delete` and `share` operations.

**Comment by wujysh** [comment]
@hackjutsu
Notification is working.

2017年2月10日 上午10:22，"Cosmo" <notifications@github.com>写道：

**Comment by hackjutsu** [comment]
@wujysh Thank you for letting me know:)
