### ISSUE TITLE
Improve the key bindings for the search bar

### ISSUE THREAD

**Issue by hackjutsu** [hackjutsu/Lepton#90]
Can we use `arrow` keys other than `Shift + arrow` keys for navigation? And also `enter` for selection?

http://stackoverflow.com/questions/42036865/react-how-to-navigate-through-list-by-arrow-keys

**Comment by wujysh** [comment]
Yes, 'shift' is not necessary.

2017年2月10日 上午6:55，"Cosmo" <notifications@github.com>写道：

**Comment by hackjutsu** [comment]
Fixed:https://github.com/hackjutsu/Lepton/commit/81befb5699c969e651a216e9a9592a0205cda6d2
