### ISSUE TITLE
Support searching for file name.

### ISSUE THREAD

**Issue by Akagi201** [hackjutsu/Lepton#94]
I have many old gists. They only have file name and no description.

So please support searching for filename.

BTW, I wish to support searching for the content as an option.(Please tell me why you don't add this function)

**Comment by hackjutsu** [comment]
@Akagi201  Thank you for the ticket:)

Searching for filename is a legitimate request, and I'll add this support in the next release.

Please refer to https://github.com/hackjutsu/Lepton/issues/82 for the reason why content search is not supported. In short, either GitHub Gist API need to provide support for remote content search, or we implement a local content search with huge performance compromise.

**Comment by hackjutsu** [comment]
Done: https://github.com/hackjutsu/Lepton/commit/6df8467a5c139ab1547aa2249ab704de7ca3e000

**Comment by hackjutsu** [comment]
@Akagi201 I can build an internal release(v1.1.2) for you. Which platform do you work on? macOS or windows?

**Comment by Akagi201** [comment]
@hackjutsu MacOS thanks. I will test it.

**Comment by hackjutsu** [comment]
@Akagi201 https://share.weiyun.com/f2ceb73753c7e89154ca501ff234e31c

**Comment by Akagi201** [comment]
@hackjutsu The filename search function works, and searched very quickly.

Additionally, I hope when I jump to the searched file. The gist list can scroll to the according gist name.

**Comment by hackjutsu** [comment]
@Akagi201 

Just want to clarify. Do you mean the gist list should scroll to the pink box once you jump to the selected gist?

![image](https://cloud.githubusercontent.com/assets/7756581/22959707/3bde6dfa-f2ed-11e6-88c7-7fcd32dcdca7.png)

**Comment by Akagi201** [comment]
@hackjutsu Yes, That's it. It's like the feature in IDEAs.

<img width="409" alt="screen shot 2017-02-15 at 13 15 10" src="https://cloud.githubusercontent.com/assets/1207959/22961436/e1fba462-f380-11e6-820e-4a4030b58fa4.png">

**Comment by hackjutsu** [comment]
Thanks for feedback:)

I created an issue ticket for that https://github.com/hackjutsu/Lepton/issues/111.
