### ISSUE TITLE
Interested in featuring Lepton on the Electron website?

### ISSUE THREAD

**Issue by zeke** [hackjutsu/Lepton#95]
@felixrieseberg told me about this app today. I hadn't seen it before. Would you be interested in featuring it on the Electron website? If so, take a look at https://github.com/electron/electron-apps/blob/master/contributing.md

:v:

**Comment by hackjutsu** [comment]
@zeke My pleasure:)

**Comment by zeke** [comment]
http://electron.atom.io/apps/?q=lepton

It's on there! This is good to close.

**Comment by hackjutsu** [comment]
Bravo! 

Thanks @zeke for the invitation, and @felixrieseberg for the recommendation:)
