### ISSUE TITLE
Submit button in new gist modal can be clicked multiple times and create duplicate gists

### ISSUE THREAD

**Issue by wujysh** [hackjutsu/Lepton#96]
The submit button should be disabled after clicked.
While waiting server response, some prompt should be given to user.
Otherwise, especially in bad network environment, user will click multiple times and create duplicate gists.

**Comment by hackjutsu** [comment]
Good catch!

**Comment by hackjutsu** [comment]
Should be fixed: https://github.com/hackjutsu/Lepton/commit/6aaa5ba24cd2e881acde990eb04524b0b515f013
